### ISSUE TITLE
windows adaptation issues

### ISSUE THREAD

**Issue by y26s4824k264** [ServiceWeaver/weaver#111]
![image](https://user-images.githubusercontent.com/54879886/223155573-fcc825c3-fd22-4747-9f28-a6c72d6070d2.png)
![image](https://user-images.githubusercontent.com/54879886/223155650-2e3a4888-f5e1-40ec-9184-1a5e0134b94e.png)

**Comment by y26s4824k264** [comment]
the command is located on the wrong port

**Comment by rgrandl** [comment]
I am not sure I understand. Are you saying that the `gke` deployment is listening on the same port as the `multi` deployment?

**Comment by y26s4824k264** [comment]
the port i open 是12345 and he seems to be listening in goland IDE

**Comment by lemon-1997** [comment]
delete files on `C:\Users\Administrator\.local\share\serviceweaver\single_registry`

**Comment by rgrandl** [comment]
Fixed in #189 . Please reopen if it still doesn't work for you.
