### ISSUE TITLE
deploy the application error

### ISSUE THREAD

**Issue by y26s4824k264** [ServiceWeaver/weaver#113]
![image](https://user-images.githubusercontent.com/54879886/223173107-734ef2d6-c501-4bc5-8c0a-8a331389a529.png)

**Comment by y26s4824k264** [comment]
![image](https://user-images.githubusercontent.com/54879886/223173272-e555aa7c-1ee8-40f3-8620-aa70128a1021.png)

**Comment by alejandrojnm** [comment]
Hi I got the same error but on mac 

```bash
filename "...2f6add44-e6ff-4bff-8d89-8ebe81a69af3.error.log" must have format "<app>.<deployment>.<weavelet>.<level>.log"
``` 

Any idea ??

**Comment by alejandrojnm** [comment]
@mwhittaker I put the name and I got the same error this is the toml file
```toml
[serviceweaver]
name = "api"
binary = "./api"
```

**Comment by mwhittaker** [comment]
Do you mind trying to delete all the log files in `/tmp/serviceweaver/logs/weaver-multi` and then trying again? The ill-formatted log file might still exist and could be messing things up.

**Comment by alejandrojnm** [comment]
I don't have that in my `tmp` folder

**Comment by aranw** [comment]
> I don't have that in my `tmp` folder 

Most likely if you are on a Mac it'll be under the `/var/folders` temporary directory

**Comment by geange** [comment]
On win11, Win+R and input `%temp%`  to open the temp dir. delete all the log files is ok !

**Comment by comyxy** [comment]
> On win11, Win+R and input `%temp%` to open the temp dir. delete all the log files is ok !

%temp%\serviceweaver\logs\weaver-multi

**Comment by mwhittaker** [comment]
I'm closing this issue because it seems resolved? Feel free to re-open if not.

**Comment by myyrakle** [comment]
I think this should also be added to the official documentation(https://serviceweaver.dev/docs.html#multiprocess).
Or, would it be difficult to apply branch handling only for windows?

Currently, it is difficult to solve without looking at this issue.

**Comment by myyrakle** [comment]
https://github.com/ServiceWeaver/weaver/pull/232

What do you think of processing in this form?
Are there side effects or other issues?
