### ISSUE TITLE
check if process is still alive when executing `weaver single/multi status` command

### ISSUE THREAD

**Issue by xwcq** [ServiceWeaver/weaver#126]
when I manually killed components' processes and then used command `weaver single/multi status`, I found the killed pids are still presented in column `REPLICA PIDS`. The corresponding codes are in file `internal/status/status.go`:
```
// formatDeployments pretty-prints the set of components.
func formatComponents(w io.Writer, statuses []*Status) {
         ...
	for _, status := range statuses {
		...
		for _, component := range status.Components {
			prefix, _ := formatId(status.DeploymentId)
			c := logging.ShortenComponent(component.Name)
			sort.Slice(component.Pids, func(i, j int) bool {
				return component.Pids[i] < component.Pids[j]
			})
			pids := make([]string, len(component.Pids))
			for i, pid := range component.Pids {
				pids[i] = fmt.Sprint(pid)
			}
			t.Row(status.App, prefix, c, strings.Join(pids, ", "))
		}
	}
}
```

Maybe check for process liveness is needed before assembling pids info. Glad to help if you think this optimization is needed.

**Comment by mwhittaker** [comment]
I think if a process dies when deployed via `weaver multi deploy`, the entire deployment should be killed. This makes it easier to see when and why things are failing.

**Comment by mwhittaker** [comment]
Op, my mistake. This behavior is actually already implemented.
