### ISSUE TITLE
Is there a plan for C++-weaver?

### ISSUE THREAD

**Issue by collinmsn** [ServiceWeaver/weaver#145]
This framework is really amazing, is there any plan for developing a C++ version?

**Comment by rgrandl** [comment]
Hi Collin,

This is a question that has better visibility if posted [here](https://groups.google.com/g/serviceweaver). See [this](https://groups.google.com/g/serviceweaver/c/IXcNidiiz8M) thread for discussions around multiple languages support.

If we decide to support multiple languages support, we will probably start with Java and Python. 

Thanks,
- Robert
