### ISSUE TITLE
An error occured while trying to run the exmaples by weaver multi deploy weaver.toml 

### ISSUE THREAD

**Issue by llgoo** [ServiceWeaver/weaver#146]
╭───────────────────────────────────────────────────╮
│ app        : collatz                              │
│ deployment : bb245bfa-1a97-4e0e-92b7-4e9d33d53621 │
╰───────────────────────────────────────────────────╯
S0310 15:22:06.728927 stderr  ea38724c           ] error initializing Service Weaver: internal error creating weavelet: new weavelet conn: string field contains invalid UTF-8
S0310 15:22:06.729157 stderr  303508ff           ] error initializing Service Weaver: internal error creating weavelet: new weavelet conn: string field contains invalid UTF-8

**Comment by collinmsn** [comment]
I got the same error. I don't know why but the problem gone after I delete .local/share/serviceweaver

**Comment by alejandrojnm** [comment]
Same here

**Comment by rgrandl** [comment]
@llgoo, can you tells us some more details about your setup? Also, is this always happening?

**Comment by llgoo** [comment]
Hi @rgrandl 
The issue was caused by outdated version of `weaver`. After I reinstalled it with the latest version using the command `go install github.com/ServiceWeaver/weaver/cmd/weaver@latest`, it started working properly.

**Comment by alejandrojnm** [comment]
Yep that solves the problem the weaver CLI and the lib need to be the same `v0.1.3`

**Comment by rgrandl** [comment]
Glad to hear that it worked. Closing the issue for now.
