### ISSUE TITLE
extending k8s manifests

### ISSUE THREAD

**Issue by viggin543** [ServiceWeaver/weaver#147]
Is it possible to integrate weaver with cloud-native tools ( like argocd , external DNS, sealed secrets ..... etc ) ?

for example:
- consider a scenario where we need to add an annotation to a k8s service weaver generates .
- or reverting the deployment using argocd ?
- Or reading an env param, from a specific k8s secret?

**Comment by batazor** [comment]
I am also interested in this point, I would like to continue to use my general methods for deploying applications (via ArgoCD and other CI/CD systems)

In general, the main question is whether this system will work correctly if you run it in its own container or whether there are requirements for kubernetes settings.

**Comment by rgrandl** [comment]
Hi @viggin543 and @batazor and all,

We implemented a vanilla Kubernetes [deployer](https://github.com/ServiceWeaver/weaver-kube) that enables to run Service Weaver applications in any Kubernetes environment.

The deployer will generate the yaml files for you, and then you can use `kubectl apply` to deploy the application. You can add annotations to the k8s services the weaver generates. 

For cloud-native tools: We are considering using [argo rollouts](https://argoproj.github.io/rollouts/) for traffic shifting. 

Which CI/CD systems do you think there are the most popular, and the community would like weaver integration with?

**Comment by viggin543** [comment]
Hi @rgrandl , very cool. will check out the new deployer.

regarding the CI/CD tools

GitHub actions for sure.

**Comment by batazor** [comment]
@rgrandl We use Argo CD/Argo Rollout - it would be cool to have some base support for this GitOps system.

We use helm/kustomize to deploy from ArgoCD - I think k8s-manifest generation is already enough to work with argocd

**Comment by rgrandl** [comment]
This is not actionable.
