### ISSUE TITLE
Having multiple implementations for an interface

### ISSUE THREAD

**Issue by agtabesh** [ServiceWeaver/weaver#149]
Hi everybody,

Having an `interface` makes sense when you have multiple `implementations`.
I wondered, how can I have multiple `implementations` for an `interface/component` and choose among them?

**Comment by mwhittaker** [comment]
Hi @agtabesh! Currently, there is no way to have multiple implementations of a component and choose among them.

We have thought about it before though, specifically in the context of testing. Our idea was to allow people to write weavertests and substitute a component implementation for a fake or mock component. We'll likely revisit this in the future! I'll close this issue for now, but if you have any good ideas for what this kind of change would look like, feel free to share!

**Comment by Multiply** [comment]
What about things with the same implementation, but different configuration?

Say we have 5 different databases we want to connect to. Some components would use 2, while others might only use 1 of them?
