### ISSUE TITLE
An error occured while trying to run the exmaples by weaver gke-local deploy weaver.toml

### ISSUE THREAD

**Issue by kiripeng214** [ServiceWeaver/weaver#159]
When i use  go install github.com/ServiceWeaver/weaver-gke/cmd/weaver-gke-local@latest and  go install github.com/ServiceWeaver/weaver/cmd/weaver@latest , to use this tutorial .
Version "eb99fc75-e9d8-4288-bc73-65523bdb3d5a" of app "hello" started successfully.
Note that stopping this binary will not affect the app in any way.
Tailing the logs...
S0314 18:01:20.394463 stderr  71addc96           ] error initializing Service Weaver: internal error creating weavelet: new weavelet conn: string field contains invalid UTF-8
S0314 18:01:20.406475 stderr  3e6318a8           ] error initializing Service Weaver: internal error creating weavelet: new weavelet conn: string field contains invalid UTF-8
S0314 18:01:20.432982 stderr  71addc96           ] error initializing Service Weaver: internal error creating weavelet: new weavelet conn: string field contains invalid UTF-8
S0314 18:01:20.447786 stderr  3e6318a8           ] error initializing Service Weaver: internal error creating weavelet: new weavelet conn: string field contains invalid UTF-8
S0314 18:01:20.475621 stderr  71addc96           ] error initializing Service Weaver: internal error creating weavelet: new weavelet conn: string field contains invalid UTF-8
 
when i use the ` weaver gke-local status`
╭──────────────────────────────────────────────────────────────────╮
│ Deployments                                                      │
├───────┬──────────────────────────────────────┬────────┬──────────┤
│ APP   │ DEPLOYMENT                           │ AGE    │ STATUS   │
├───────┼──────────────────────────────────────┼────────┼──────────┤
│ hello │ 8d0b6e69-c2fa-49c6-8f07-01d2ecc9ca7d │ 53m52s │ DELETING │
│ hello │ 60991bdc-02d8-4fb1-a6d7-124c837317cc │ 48m51s │ DELETING │
│ hello │ 6f5ce217-39a8-436c-8524-4c3865af7158 │ 47m26s │ DELETING │
│ hello │ 8942443f-2e0c-4a19-898e-15828e0ef55b │ 45m37s │ DELETING │
│ hello │ 3a46ab2a-5a2e-4486-8982-1e5d6776be98 │ 41m45s │ DELETING │
│ hello │ 45a552ba-d610-453f-930e-0f623555e1c5 │ 40m13s │ DELETING │
│ hello │ 1bac82e7-9dd3-4fa2-92a3-c31e83d5c4ea │ 33m49s │ DELETING │
│ hello │ 06d3532d-325e-4239-9417-7c464b1178f1 │ 28m36s │ DELETING │
│ hello │ a9176f47-587c-4f03-81a6-ec3a9d4155f4 │ 28m21s │ DELETING │
│ hello │ abce5cb9-d349-455c-befc-11b5e592f466 │ 27m47s │ DELETING │
│ hello │ 77088351-d631-4f49-b967-6e570fad91c4 │ 18m32s │ DELETING │
│ hello │ a48bcd83-c105-40f5-ae8d-e2e09ceafde6 │ 16m21s │ DELETING │
│ hello │ a9188e41-6a4f-4452-9511-e0ac2ac36a5e │ 14m33s │ DELETING │
│ hello │ f1353f27-52e0-4bd6-b7e4-d4742f70ce4d │ 11m21s │ DELETING │
│ hello │ e54ad469-b832-4e30-86e9-ebc4b46ecf7a │ 10m17s │ DELETING │
│ hello │ 306ba873-6bef-4110-ac46-a82a607b4c15 │ 8m15s  │ DELETING │
│ hello │ 54f956ea-effa-4584-a593-d13b2ccf7b53 │ 8m6s   │ DELETING │
│ hello │ 1c23e162-a3a5-484b-803d-1a5f713e831c │ 6m8s   │ DELETING │
│ hello │ 72972e52-6398-4140-a47c-bfffe3ec0759 │ 5m3s   │ DELETING │
│ hello │ 5193b0f1-ba8e-456e-8d7f-213e0948c226 │ 2m18s  │ DELETING │
│ hello │ eb99fc75-e9d8-4288-bc73-65523bdb3d5a │ 26s    │ ACTIVE   │
╰───────┴──────────────────────────────────────┴────────┴──────────╯
╭───────────────────────────────────────────────────╮
│ COMPONENTS                                        │
├─────┬────────────┬──────────┬───────────┬─────────┤
│ APP │ DEPLOYMENT │ LOCATION │ COMPONENT │ HEALTHY │
├─────┼────────────┼──────────┼───────────┼─────────┤
╰─────┴────────────┴──────────┴───────────┴─────────╯
╭──────────────────────────────────────────────────────────────────────────────╮
│ TRAFFIC                                                                      │
├──────┬────────────┬─────┬────────────┬──────────┬─────────┬──────────────────┤
│ HOST │ VISIBILITY │ APP │ DEPLOYMENT │ LOCATION │ ADDRESS │ TRAFFIC FRACTION │
├──────┼────────────┼─────┼────────────┼──────────┼─────────┼──────────────────┤
╰──────┴────────────┴─────┴────────────┴──────────┴─────────┴──────────────────╯
╭────────────────────────────╮
│ ROLLOUT OF hello           │
├─────────────────┬──────────┤
│                 │ us-west1 │
├─────────────────┼──────────┤
│ TIME            │ eb99fc75 │
│ Mar 14 10:01:46 │ 1.00     │
╰─────────────────┴──────────╯

curl --header 'Host: hello.com' "localhost:8000/hello?name=Weaver"
host "hello.com" not found

**Comment by spetrovic77** [comment]
This is likely caused by some breaking changes we introduced.

@kiripeng214 Are you cloning the `weaver` repo and running examples it contains? If so, could you checkout the latest stable version, which is currently v0.1.5, and re-compile the `hello` binary:

```console
$ git checkout v0.1.5
$ cd examples/hello
$ go build .
```

If you're working in your own repo on the other hand, change the `go.mod` file to depend on `weaver@0.1.5`, and re-compile the `hello` binary.

After that, please download the latest version of weaver-gke-local:

`$ go install github.com/ServiceWeaver/weaver-gke/cmd/weaver-gke@v0.1.5`

(In theory, `go install github.com/ServiceWeaver/weaver-gke/cmd/weaver-gke@latest` should work as well.)

Things should work after these steps are followed. Please let us know if they don't.

**Comment by kiripeng214** [comment]
> This is likely caused by some breaking changes we introduced.
> 
> @kiripeng214 Are you cloning the `weaver` repo and running examples it contains? If so, could you checkout the latest stable version, which is currently v0.1.5, and re-compile the `hello` binary:
> 
> ```
> $ git checkout v0.1.5
> $ cd examples/hello
> $ go build .
> ```
> 
> If you're working in your own repo on the other hand, change the `go.mod` file to depend on `weaver@0.1.5`, and re-compile the `hello` binary.
> 
> After that, please download the latest version of weaver-gke-local:
> 
> `$ go install github.com/ServiceWeaver/weaver-gke-local/cmd/weaver-gke-local@v0.1.5`
> 
> (In theory, `go install github.com/ServiceWeaver/weaver-gke-local/cmd/weaver-gke-local@latest` should work as well.)
> 
> Things should work after these steps are followed. Please let us know if they don't.

Thanks!,it can work.
