### ISSUE TITLE
Remove $ sign from docs commands

### ISSUE THREAD

**Issue by moficodes** [ServiceWeaver/weaver#165]
the doc has $ signs in the beginning. While its visually appealing it makes copying the command difficult.

Either we remove the dollar sign all the commands or make the copy button no copy the $ sign.

```bash
$ go run .                      # Run locally.
$ weaver gke deploy weaver.toml # Run in the cloud.
```

**Comment by spetrovic77** [comment]
Thanks for reporting, we have a PR in progress that fixes the issue.
