### ISSUE TITLE
weaver multi deploy is failure

### ISSUE THREAD

**Issue by veterancj** [ServiceWeaver/weaver#179]
step1:   weaver multi deploy weaver.toml
╭───────────────────────────────────────────────────╮
│ app        : hello                                │
│ deployment : cb92a3e5-a956-46ff-86ac-269d7b09b0c9 │
╰───────────────────────────────────────────────────╯
S0321 15:16:50.243458 stdout  567250c1           ] hello listener available on 127.0.0.1:12345
S0321 15:16:50.243765 stdout  020d2067           ] hello listener available on 127.0.0.1:12345

step2: curl "localhost:12345/hello?name=Weaver"
keep blocking

step3: weaver multi status
╭──────────────────────────────────────────────────────╮
│ DEPLOYMENTS                                          │
├───────┬──────────────────────────────────────┬───────┤
│ APP   │ DEPLOYMENT                           │ AGE   │
├───────┼──────────────────────────────────────┼───────┤
│ hello │ cb92a3e5-a956-46ff-86ac-269d7b09b0c9 │ 3m56s │
╰───────┴──────────────────────────────────────┴───────╯
╭───────────────────────────────────────────────╮
│ COMPONENTS                                    │
├───────┬────────────┬───────────┬──────────────┤
│ APP   │ DEPLOYMENT │ COMPONENT │ REPLICA PIDS │
├───────┼────────────┼───────────┼──────────────┤
│ hello │ cb92a3e5   │           │              │
│ hello │ cb92a3e5   │ main      │ 15208, 15209 │
╰───────┴────────────┴───────────┴──────────────╯
╭─────────────────────────────────────────────────╮
│ LISTENERS                                       │
├───────┬────────────┬──────────┬─────────────────┤
│ APP   │ DEPLOYMENT │ LISTENER │ ADDRESS         │
├───────┼────────────┼──────────┼─────────────────┤
│ hello │ cb92a3e5   │ hello    │ 127.0.0.1:12345 │
╰───────┴────────────┴──────────┴─────────────────╯

component only one , expect two.

**Comment by mwhittaker** [comment]
Could you also try the following steps. First, delete the following directories. Note that doing so will delete any history of any Service Weaver apps you're running locally.

```console
rm -r ~/.local/share/serviceweaver/
rm -r /tmp/serviceweaver/
```

Next, make sure that the weaver tool and the compiled Service Weaver binary are at the latest version. If your application binary is at the latest version, but the weaver multi deploy command is stale, things will break. To do this, re-run the following command:

```
go install github.com/ServiceWeaver/weaver/cmd/weaver@latest
```

And in the `go.mod` file in your application, make sure you're using the latest version of Service Weaver.

If the problem persists after all this, please let me know!

**Comment by rgrandl** [comment]
@veterancj the issue should be fixed. If not, please reopen the issue.
