### ISSUE TITLE
Is there any other communication channel apart of github where ServiceWeaver usage can be discussed?

### ISSUE THREAD

**Issue by vpakhuchyi** [ServiceWeaver/weaver#209]
Hi there!

I'm learning how to work with ServiceWeaver and obviously have some questions that aren't covered in https://serviceweaver.dev.
Is there any communication channel that can be used for expertise sharing? 

Many thanks!

**Comment by mwhittaker** [comment]
Hi @vpakhuchyi! Thanks for checking out Service Weaver. In addition to GitHub, we have a [Google Group](https://groups.google.com/g/serviceweaver). You can also email the team directly at serviceweaver@google.com. You can find these links on our website at https://serviceweaver.dev/contact.html.
