### ISSUE TITLE
Q: In a multi process deployment, can I adjust the number of replias?

### ISSUE THREAD

**Issue by myyrakle** [ServiceWeaver/weaver#233]
I'm using it according to the official documentation. I have a question because I couldn't find a part where I could set up a replica.

P.S. It would be nice to have a Discussion for Q&A...

**Comment by mwhittaker** [comment]
Hi @myyrakle. There is no easy way to adjust the number of replicas. Here's the code that defines the number of replicas: 

https://github.com/ServiceWeaver/weaver/blob/2c48ca8f415cb9dba82ce28b854957512789c0e2/internal/tool/multi/deployer.go#L48

If you want, you can edit the source code and recompile the `weaver` tool. 

We could allow users to configure the number of replicas. If you don't mind sharing, what were you trying to accomplish by changing the number of replicas?

**Comment by mwhittaker** [comment]
> P.S. It would be nice to have a Discussion for Q&A...

I've never used GitHub Discussions before. We have [a Google Group for Q&A right now](https://groups.google.com/g/serviceweaver), but maybe Discussions are better? What has your experience been with Discussions vs Google Groups?

**Comment by myyrakle** [comment]
I didn't need that feature right away.
However, if the function to adjust the number of processes is provided, I think that users will be able to make the most of their resources within the limit.

What do you think of handling these values ​​in `weaver.toml`?

**Comment by myyrakle** [comment]
Personally, the experience of github discussion was simple and good.
And it's also very visible. 
In addition, it was nice to be able to write an article right away without additional login.

**Comment by mwhittaker** [comment]
> What do you think of handling these values ​​in weaver.toml?

**Comment by mwhittaker** [comment]
> What do you think of handling these values ​​in weaver.toml?

We've been trying to keep config files as minimal as possible, but if we find there's a lot of desire to specify the number of replicas for a multiprocess deployment, we can definitely add it! 

> Personally, the experience of github discussion was simple and good.

Awesome, thanks so much for sharing. I'll chat with the team about enabling Discussions then. It sounds nice.
