### ISSUE TITLE
slog.Handler not implemented

### ISSUE THREAD

**Issue by naivary** [ServiceWeaver/weaver#240]
Hi,

../../go/pkg/mod/github.com/!service!weaver/weaver@v0.3.0/runtime/logging/logger.go:85:9: cannot use h (variable of type *LogHandler) as slog.Handler value in return statement: *LogHandler does not implement slog.Handler (wrong type for method Handle)
                have Handle(slog.Record) error
                want Handle(context.Context, slog.Record) error

The handler used in the package is correct with the corresponding interface signature but the newer version of slog is using another Handle method signature. This leads to the error above. I'm doing something wrong while installing weaver on my local machine?

**Comment by mwhittaker** [comment]
Hi @naivary, thanks so much for reporting this. It looks like our code depends on a stale version of the `exp/slog` module from 02/06/2023:

https://github.com/ServiceWeaver/weaver/blob/2c48ca8f415cb9dba82ce28b854957512789c0e2/go.mod#L25

We'll work on updating the code to the latest version of `exp`.

**Comment by naivary** [comment]
My pleasure to contribute. I would like to contribute to the project but I have no idea where to start for the beginning to? I already read some main parts of the code and understood it (thanks for the nice written code and docs). Should I start with an issue first or try something else?
