### ISSUE TITLE
GKE: Rolling update doesn't work well 

### ISSUE THREAD

**Issue by myyrakle** [ServiceWeaver/weaver#241]
Rolling update doesn't work well in gke.

In my opinion, if I redeploy with the same toml configuration, weaver should basically do a rolling update with no downtime.
If not, please correct me.

So, currently I have implemented the health check API in the form of "GET /".

And actually, the old version of the deployment is going down based on the health check.

The problem is that switching between versions of the server is not done non-disruptively.

![image](https://user-images.githubusercontent.com/16988115/230770381-9ee29867-8d76-41b3-8547-a220a42c21bc.png)

A load balancing error occurs for a while as above.
What could be the problem?

```
# weaver.toml
[serviceweaver]
name = "weaver-start"
binary = "./weaver-start"

[gke]
regions = ["asia-northeast3"]
public_listener = [
  {name = "weaver-start", hostname = "myyrakle.com"},
]
```

**Comment by spetrovic77** [comment]
Hi @myyrakle,

Thanks for pointing this out, this is a known issue. As far as we can tell, we're updating the [external load-balancer](https://cloud.google.com/load-balancing/docs/https) gradually and with the right set of traffic shares, but it does error out for a brief period of time during the traffic change.

We're working on resolving this issue. And you're right, the intention is that you just set the rollout period in your configuration file and the framework ensures that the new version is deployed gradually and safely, without any service interruption.

**Comment by rgrandl** [comment]
We did some fixes that should make the rolling update experience much better.
