### ISSUE TITLE
Are there plans to further expand the scope of GKE management capabilities?

### ISSUE THREAD

**Issue by myyrakle** [ServiceWeaver/weaver#259]
Perhaps currently only the following features are available:

1. Initializing the Kubernetes cluster and other GCP components when performing `weaver gke deploy` for the first time
2. Adding/updating pods to the Kubernetes cluster when the app is deployed
3. Delete pods when app is uninstalled

I would like to see the following features added:

1. Cleanup of all GCP components
-> For those who first encounter weaver through the tutorial, most will test it for a while and then remove the test environment.
For now, it looks like I'll probably have to clear it myself.
Wouldn't it be nice if we could explicitly do gke init/cleanup via weaver-cli?

2. Inquiry/change of GCP infrastructure resources controlled by weaver
-> Like terraform, if we can check and discern which resources are controlled by weaver, it will be helpful for ongoing infrastructure management.

What do you think about this?

**Comment by rgrandl** [comment]
This has been partially addressed. The remaining work has been deprioritized.
