### ISSUE TITLE
Cannot run examples/hello out of the box

### ISSUE THREAD

**Issue by abiabsurd** [ServiceWeaver/weaver#276]
Essentially I did
```zsh
git clone git@github.com:ServiceWeaver/weaver.git
cd weaver/examples/hello
go mod init hello
go mod tidy
weaver generate .
go run .
```
and got output
```
hello listener available on 127.0.0.1:12345
panic: http: multiple registrations for /healthz
```
followed by a stack trace pointing [here](https://github.com/ServiceWeaver/weaver/blob/main/examples/hello/main.go#L57).

Have I missed a step? Is it not expected that I could run the example like that? Where is that prior call to register `/healthz` happening?

**Comment by mwhittaker** [comment]
Whoops! That's our bad. I'm working a quick fix, and the team is working on more thorough fix. 

The context is that the GKE deployer requires an app to export a `/healthz` endpoint. The weaver package registers a `/healthz` endpoint with the default HTTP mux:

https://github.com/ServiceWeaver/weaver/blob/59a308d4c210205b848b54db73bf9478c0523c77/weaver.go#L88-L91

We recently changed the hello app to register a `/healthz` endpoint with the mux as well, which caused the panic. For now, I'll revert the change we made to the hello app. In the longer term, we'll probably change the weaver package to not automatically register a `/healthz` endpoint at all.
