### ISSUE TITLE
Ref is unresolved type

### ISSUE THREAD

**Issue by olezhek28** [ServiceWeaver/weaver#303]
Hello! I tried to run hello example, but had error.

I used go-code from "step by step" article - https://serviceweaver.dev/docs.html#installation:~:text=executed%20as%20RPCs.-,Multiple%20Components,-In%20a%20Service

```
package main

import (
    "context"
    "fmt"
    "log"

    "github.com/ServiceWeaver/weaver"
)

func main() {
    if err := weaver.Run(context.Background(), serve); err != nil {
        log.Fatal(err)
    }
}

type app struct{
    weaver.Implements[weaver.Main]
    reverser weaver.Ref[Reverser]
}

func serve(ctx context.Context, app *app) error {
    // Call the Reverse method.
    var r Reverser = app.reverser.Get()
    reversed, err := r.Reverse(ctx, "!dlroW ,olleH")
    if err != nil {
        return err
    }
    fmt.Println(reversed)
    return nil
}
```

My IDE said me about `reverser weaver.Ref[Reverser]`, that Ref is unresolved type. Also in hello example in repo there is other code.

**Comment by mwhittaker** [comment]
Hi @olezhek28, if you upgrade to the latest weaver version (by running `go install github.com/ServiceWeaver/weaver/cmd/weaver@latest` and by updating the version in your `go.mod` to `@latest`), do things work now?

**Comment by mwhittaker** [comment]
I'm closing this issue, but feel free to re-open if the problem persists.
