### ISSUE TITLE
Error Running Latest Version of 'Weaver': Updating 'Slog' Package and 'Weaver Generate' Command Not Responding

### ISSUE THREAD

**Issue by ryan961** [ServiceWeaver/weaver#331]
1. When using the latest version of `weaver`, an error occurs (indicating that the version of the `slog` package needs to be updated).
```bash
➜  go run .        
# github.com/ServiceWeaver/weaver
vendor/github.com/ServiceWeaver/weaver/singleprocess.go:327:66: slog.HandlerOptions{…}.NewTextHandler undefined (type slog.HandlerOptions has no field or method NewTextHandler)
vendor/github.com/ServiceWeaver/weaver/weavelet.go:112:69: slog.HandlerOptions{…}.NewTextHandler undefined (type slog.HandlerOptions has no field or method NewTextHandler)
```

2.  `weaver generate` doesn't respond for a long time and there is no output on the command line. Below is a simple reproducing code. I'm not sure if my way of opening it is correct.

go version: 1.20.4
weaver: 0.10.0

**Comment by ryan961** [comment]
I tried using `weaver generate . ./bff` as instructed in the documentation, but it seemed to hang with no response, and I had to forcefully terminate the command using `ctrl + c`. However, I found that using `go generate weaver generate ./...` generated the code directly without any issues.

**Comment by ryan961** [comment]
Thank you for the reply. Regarding the first question, the issue should be resolved in the next version with the merging of the pull request (#333) . However, the second question is unrelated to this particular submission. Today, I followed the official tutorial (https://serviceweaver.dev/docs.html#step-by-step-tutorial-components) and tested it (`$ weaver generate .`) in a new environment, but I still encountered the same problem (the command hangs without any response) . I attempted to debug it and it seems to be stuck at [`pkgList, err := packages.Load(cfg, pkgs...)`](https://github.com/ServiceWeaver/weaver/blob/d2179635a1d0d4d5656cd5993a0c8963c7009d26/internal/tool/generate/generator.go#L109).

**Comment by mwhittaker** [comment]
Thanks for investigating further @ryan961! Sorry you're running into this problem. First, can you share the output of `weaver multi version`? 

I wasn't able to reproduce the issue locally, and our GitHub actions also run `weaver generate` without any issue, so it's a bit tricky to debug. Hanging in `packages.Load` is also strange. Is it possible that `packages.Load` is just slow for some reason? Maybe you could add a print after the `packages.Load` call and let it run for a while? If you want, you could also create a little GitHub repo that reproduces the bug, and I can try to clone it and see if I have the same issue.

**Comment by ryan961** [comment]
Thank you. Today, I also tried testing it using github action (https://github.com/ryan961/weaverhello/actions/runs/5000742013/jobs/8958536074) and a fresh Ubuntu machine separately, but I couldn't reproduce the issue (`weaver generate .` worked fine). I suspect that it's likely an issue with my local environment (such as the usage of the package version management tool `asdf`...). For now, I will close this issue. If there is any new feedback or discoveries in the future, I will communicate them through the new issue again
