### ISSUE TITLE
runner.Test undefined (type weavertest.Runner has no field or method Test

### ISSUE THREAD

**Issue by Markbnak** [ServiceWeaver/weaver#369]
I'm running weaver v0.12.

I followed the [official documentation](https://serviceweaver.dev/docs.html#testing) to create tests.

I use a similar code:

```
func TestAdd(t *testing.T) {
     runner := weavertest.Local  // A runner that runs components in a single process
     runner.Test(t, func(t *testing.T, adder Adder) {
         ctx := context.Background()
         got, err := adder.Add(ctx, 1, 2)
         if err != nil {
             t.Fatal(err)
         }
         if want := 3; got != want {
             t.Fatalf("got %q, want %q", got, want)
         }
     })
}
```

It seems like weavertest.Local.Test does not exist.

`runner.Test undefined (type weavertest.Runner has no field or method Test)`

**Comment by Youyou23** [comment]
Running onto the same issue. 
I've tried also with version v0.10 => same compilation error ...

**Comment by mwhittaker** [comment]
Ah, this is unfortunately a known problem with our online documentation. The docs reflect the main branch of our repo which is ahead of the latest version (0.12.0 in this case). We'll release v0.13.0 soon which should fix the problem. We'll also work on changing the online docs to reflect the latest version. Sorry for this!

**Comment by mwhittaker** [comment]
This should be fixed now! I'll close the issue, but please re-open if the problem persists.

**Comment by Markbnak** [comment]
Thank you for this, it works now with version v0.13.0
