### ISSUE TITLE
[Discussion]                               ServiceWeaver as Distributed Monolith

### ISSUE THREAD

**Issue by g41797** [ServiceWeaver/weaver#375]
"A long time ago in a galaxy far, far away...." [CORBA](https://en.wikipedia.org/wiki/Common_Object_Request_Broker_Architecture) provided similar approach. 

And failed.One reason - when you build complex application and base negotiation between modules on methods/calls (object oriented style) instead of messages, you cannot achieve clean separation. Moreover you forget about networking, timing etc. 

Negotiation between modules should be explicit, this is the only way to force developer to design application as set of undependable "network" components
 
With the same cost instead of interfaces, you can provide typed mailboxes and similar abstractions for negotiation. 

ServiceWeaver tries to solve problem of convenient development and deployment of microservices. 
But it didn't prevent building of distributed monolith
It doesn't change mindset

**Comment by spetrovic77** [comment]
Hi @g41797,

Thank you for starting a discussion here. We received many similar statements, some from experts in distributed systems.

@mwhittaker wrote a response as a blog [here](https://serviceweaver.dev/blog/corba.html). If you have time, we would welcome you to read it and share your thoughts back here.

**Comment by g41797** [comment]
first of all - thank you for small response latency
second - great blog and specially links within

"...is a mistake to try to isolate the programmer from the fundamental issues of remote calls" - I agree that ServiceWeaver helps to solve some problems of remote calls

but my point is different - not only remote calls are bad, **_any type of CALL is bad (local&remote)_**

message oriented paradigm is hard, but it's only way to change mind set and force developer/designer really decouple parts of the system.

Yesterday I saw some youtube videos and unknown terminology raised my attention - _modular monolith_ - best solution etc, etc
I dived dipper (because I also didn't know what monolith is) and dipper (microservices - also silver bullet)

one link pointed to serviceweaver

what i understood:

- a lot of applications were developed as monolith
- microservices were created to solve problem of monolith (and other problems..)
- develop microservices is not easy task
- serviceweaver simplifies development/deployment of microservices and improves system stability
- but (from my point of the view) it doesn't change way of design 

and it turned out that last 30 years i developed modular monoliths

**Comment by g41797** [comment]
btw i opened new issue [How to build modular monolith](https://github.com/ThreeDotsLabs/watermill/issues/368) in another project

please take a look, possibly it will explain better what is the real problem
(and i don't participate in this project)

**Comment by g41797** [comment]
[Discussion - discord](https://discordapp.com/channels/1091097749488926790/1091097749488926793/1116467050408333342)

**Comment by mwhittaker** [comment]
Closing the issue since the discussion moved to discord.
