### ISSUE TITLE
Add async request-response

### ISSUE THREAD

**Issue by g41797** [ServiceWeaver/weaver#381]
some days ago i opened #375 and [discord discussion](https://discordapp.com/channels/1091097749488926790/1091097749488926793/1116467050408333342)
main point - transparency of call (local/remote) doesn't help to turn a monolith into a component.

let's give a chance to developer act differently:
additionally or instead of call interface
```go
type LocalCache interface {
	Get(_ context.Context, key string) (string, error)
	Put(_ context.Context, key, val string) error
}
```
should be possible to use "**_request-response_**" and develop code as remote 

```go
type LocalCache interface {
	Get(_ context.Context, key string, respval chan string, resperr chan error)
	Put(_ context.Context, key, val string, resperr chan error)
}
```
of course i don't ask marshall/unmarshall chan   

btw i liked blog [here](https://serviceweaver.dev/blog/corba.html)

**Comment by mwhittaker** [comment]
Hi @g41797! In our experience, we've found it better to avoid using channels in APIs and instead let the user wrap synchronous APIs in goroutines when they need to. For example, you can always do the following:

```go
respval := make(chan string)
resperr := make(chan err)
go func() {
    val, err := cache.Get(ctx, key)
    respval <- val
    resperr <- err
}() 
```

And glad you liked the blog :)
