### ISSUE TITLE
Weaver generate doesn't ignore the "weaver_gen.go" file while parsing pkgs

### ISSUE THREAD

**Issue by songsy13** [ServiceWeaver/weaver#383]
Hi, I define a golang struct embeded the `weaver.Automarshal`and run `weaver generate ./...` in my project dir, and it generates a weaver_gen.go file which includes the `WeaverMarshal` and `WeaverUnmarshal` methods of that struct. 
```
type Embed struct {
	weaver.AutoMarshal
	d1 int
	d2 int
	str   string
	slice []string
	kv map[string]int
}

func (x *Embed) WeaverMarshal(enc *codegen.Encoder) {
	if x == nil {
		panic(fmt.Errorf("Embed.WeaverMarshal: nil receiver"))
	}
	enc.Int(x.d1)
	enc.Int(x.d2)
	enc.String(x.str)
	serviceweaver_enc_slice_string_4af10117(enc, x.slice)
	serviceweaver_enc_map_string_int_c20ee031(enc, x.kv)
}

func (x *Embed) WeaverUnmarshal(dec *codegen.Decoder) {
	if x == nil {
		panic(fmt.Errorf("Embed.WeaverUnmarshal: nil receiver"))
	}
	x.d1 = dec.Int()
	x.d2 = dec.Int()
	x.str = dec.String()
	x.slice = serviceweaver_dec_slice_string_4af10117(dec)
	x.kv = serviceweaver_dec_map_string_int_c20ee031(dec)
}
```

However when I delete a field defined in the struct and re-run `weaver generate ./...`, it returns the following errors:
```
type Embed struct {
	weaver.AutoMarshal
	d1    int
	d2    int
	//str   string  // delete this field 
	slice []string
	kv    map[string]int
}
```

```
model/weaver_gen.go:28:15: x.str undefined (type *Embed has no field or method str)
model/weaver_gen.go:39:4: x.str undefined (type *Embed has no field or method str)
```
I have to manually delete the `weaver_gen.go` file first and then run `weaver generate` if I change any field of a struct. I  think that is probably not very reasonable :(

When I read the `generate` source code, I find out that there is a `parseNonWeaverGenFile` function whose purpose is to ignore the `weaver_gen.go` file. So I'm confused if the aboving errors are expected ?

**Comment by mwhittaker** [comment]
Great catch. That's a bug. I'll work on fixing it.

**Comment by mwhittaker** [comment]
Hi @songsy13, I'm having trouble reproducing the bug. Could you share a minimal example and the steps you're running to produce the bug? Also note that if you delete a field from your `Embed` struct, `go build` should fail until you re-run `weaver generate`. That is intentional. `weaver generate` should succeed though.

**Comment by songsy13** [comment]
Hi @mwhittaker , I add a model package in examples/hello directory, like this:
```
.
├── README.md
├── hello
├── main.go
├── model
│   ├── model.go
│   └── weaver_gen.go
├── reverser.go
├── weaver.toml
└── weaver_gen.go
```

`model.go` includes a simple struct `Embed`:
```
type Embed struct {
	weaver.AutoMarshal
	num int
	str string
}
```
I installed the latest `weaver cmd` shown from the `weaver version` cmd:
```
weaver v0.14.0
target: darwin/arm64
commit: ?
deployer API: 0.14.0
codegen API: 0.11.0
```
I ran `weaver generate ./...` in the `hello` directory, and it generates a `weaver_gen.go` file in the `model`  package directory. Then I deleted the `str` field in the `Embed` struct and re-ran `weaver generate ./...`, it returned the following errors:
```
-: # github.com/ServiceWeaver/weaver/examples/hello/model
model/weaver_gen.go:33:18: Embed does not satisfy ~struct{weaver.AutoMarshal; num int; str string} (Embed missing in ~struct{github.com/ServiceWeaver/weaver.AutoMarshal; num int; str string})
model/weaver_gen.go:40:15: x.str undefined (type *Embed has no field or method str)
model/weaver_gen.go:48:4: x.str undefined (type *Embed has no field or method str)
```

**Comment by mwhittaker** [comment]
Thanks so much @songsy13! I was very easily able to reproduce the bug (I'm actually confused about why I wasn't able to reproduce it earlier). I opened #387 which should fix things!
