### ISSUE TITLE
"Code generated by .*" comment should appear before package clause

### ISSUE THREAD

**Issue by itstarsun** [ServiceWeaver/weaver#411]
https://go.dev/s/generatedcode
> To convey to humans and machine tools that code is generated, generated source should have a line that matches the following regular expression (in Go syntax):
`^// Code generated .* DO NOT EDIT\.$`
This line must appear before the first non-comment, non-blank text in the file.

**Comment by mwhittaker** [comment]
Thanks @itstarsun! Good find!
