### ISSUE TITLE
How to properly make dependency injection with ServiceWeaver

### ISSUE THREAD

**Issue by Markbnak** [ServiceWeaver/weaver#419]
I'm trying to implement the dependency injection pattern in my code.

I need it because we need to mock results from an external API during tests.

Here is a sample of what I'm trying to achieve:

**Service calling external data**
```go
// get external data service
package service

type GetExternalDataService interface {
	GetData(ctx context.Context, value string)
}

type getExternalDataServiceImpl struct {
	weaver.Implements[]
}

func GetData(ctx context.Context, value string) {
  // getting the actual external data //
}
```
**Service**
```go
// service
package service
var Dependency_fn DepFunc

type DepFunc func(ctx context.Context, x string, y string)

type someService interface {
	GetSomeExternalData(ctx context.Context, value string)
}

type someServiceImpl struct {
	weaver.Implements[]
	externalService weaver.Ref[service.GetExternalDataService]
}

func (s *someServiceImpl) GetSomeExternalData(ctx context.Context, value string) {
	// calling external API //
	DepFunc(ctx, "some data")
}
```
**Tests**
```go
// tests
package service

func mock_external_data(ctx context.Context, data string) {
  // returns mock data //
}

func setupTest(t *testing.T) {
	t.Helper()
	Dependency_fn = mock_external_data
}


func TestGetSomeExternalData(t *testing.T) {
	setupTest(t)

	runner := weavertest.Local
	runner.Test(t, func(t *testing.T, rate RateService) {

		ctx := context.Background()
		got, err := service.GetSomeExternalData(ctx, "some value")
		if err != nil {
			t.Fatal(err)
		}

		if want := what_I_want; !got.Equal(want) {
			t.Fatalf("got %q, want %q", got, want)
		}
	})
}
```
**The calling service**
```go
// other service
package secondService

type SecondService struct {
  SendReceivedData(ctx context.Context)
}

type secondServiceImpl struct {
  SendReceivedData(ctx context.Context)
  service weaver.Ref[service.someService]
}

func (s *secondServiceImpl) Init(ctx context.Context) error {
  s.service.Dependency_fn = service.GetExternalDataService
}


func (s *secondServiceImpl) SendReceivedData(ctx context.Context) {
  received, err := s.service.GetSomeExternalData(ctx, "some data")
  // other code //
}
```

The whole problem is how to tell the `service` package which `Dependency_fn` function to use when calling it from `secondService` package.

The tests I developed work perfectly and I am able to use the mock function.

I read a similar issue: #188 

In the discussion it is suggested to use `weaver.Get[Foo]`, but this provides me compilation errors such as:
`undefined: weaver.get`

For these examples I tried versions v0.13.0 and v0.16.0.

**Comment by mwhittaker** [comment]
Hi @Markbnak, does [`weavertest.Fake`](https://pkg.go.dev/github.com/ServiceWeaver/weaver/weavertest#Fake) suit your use case? You can see an example of `weavertest.Fake` in use [here](https://github.com/ServiceWeaver/weaver/blob/main/examples/chat/server_test.go#L79C1-L107). Let me know if you have any questions about how it works and how you're supposed to use it.

**Comment by Markbnak** [comment]
Thank you for sharing this, I haven't seen that feature in the documentation.

**Comment by Markbnak** [comment]
@mwhittaker I managed to resolve my issue, [this code example](https://github.com/ServiceWeaver/weaver/blob/main/examples/chat/server_test.go#L79C1-L107) was what I was looking for. I hope you will document that on your website.

**Comment by mwhittaker** [comment]
Awesome! I opened #430 for this as well!
