### ISSUE TITLE
Issues with Logging Functionality and Incomplete Logs in Weaver Multi Deployment

### ISSUE THREAD

**Issue by ryan961** [ServiceWeaver/weaver#468]
weaver version:  weaver v0.17.0

1. The Logging functionality within Weaver does not support predefined configurations (such as setting the default `Handler` to `NewJSONHandler`), which poses a great inconvenience for me as I intend to independently deploy a single process using the built-in `s.Logger()` and collect logs.
2. When using the built-in Logger and deploying with Weaver Multi, the logs collected through the command `weaver multi logs --format=json` are incomplete, as the fields I added using `s.Logger().With(slog.String("logType", "attribute"))` are missing.
Default output when deploying with `weaver multi deploy weaver.toml`:
![image](https://github.com/ServiceWeaver/weaver/assets/32825698/6317716a-e6e5-4279-bc7e-457a8dcf7f45)
What I see when using `weaver multi logs --format=json`:
![image](https://github.com/ServiceWeaver/weaver/assets/32825698/9e02b6fd-e3ca-47a0-87c5-958bd4b989a1)

**Comment by mwhittaker** [comment]
I opened PR #470 to address your second point. Great catch! 

Do you mind elaborating on your first point? I'm not sure I fully understand. Are you saying that calling the `Logger` method on a component implementation should return the logger set by `slog.SetDefault`?

**Comment by ryan961** [comment]
Thank you for your timely reply and the PR fix, @mwhittaker.

Indeed, it is somewhat similar to the functionality of `slog.SetDefault`, which allows me to customize the `slog.Logger` in `weaver.Main`. For example, setting a custom `io.Writer` (such as `os.File`...), using `slog.NewJSONHandler` instead of `slog.NewTextHandler` by default, and utilizing `slog.ReplaceAttr()` for field manipulation or even data obfuscation...

I noticed that the documentation only briefly explains the logging for single processes (https://serviceweaver.dev/docs.html#single-process-logging), and upon inspecting the source code (v0.17.0), it seems that the logger is hardcoded as `slog.New(slog.NewTextHandler(os.Stdout, &slog.HandlerOptions{Level: slog.LevelError + 1}))`(https://github.com/ServiceWeaver/weaver/blob/b181a14717694b15882d7fc23af405292a07118a/weavelet.go#L130). Although `weaver multi logs ` can support most of the mentioned requirements, it is not very convenient for single-process deployments and development debugging stages.

I am delighted to discover that the `weaver.SetLogger` feature module has been added in today's commit. I am eagerly anticipating the release of the new version. 🥳

**Comment by mwhittaker** [comment]
Got it, thanks for elaborating! Rather than adding new APIs to the weaver package, is it possible to implement your own logger that wraps the logger returned by a component's `Logger` method? Maybe something like the following?

```go
type exampleComponent struct {
     weaver.Implements[ExampleComponent]
     logger *slog.Logger
}

func (e *exampleComponent) Init(context.Context) error {
    myHandler := makeCustomHandler(e.Logger().Handler)
    e.logger = slog.New(myHandler)
    return nil
} 
```

Here, `makeCustomHandler` returns a `slog.Handler` that does whatever custom logic you need before forwarding a `slog.Record` to `e.Logger().Handler`.

Also, sadly, the new `SetLogger` function is internal and will not be callable.

**Comment by ryan961** [comment]
Haha, it's alright. Please forgive me for not carefully examining the source code. .
I am extremely grateful for the excellent solution you have provided. I will implement it in my project.
