### ISSUE TITLE
Restrict service instances 

### ISSUE THREAD

**Issue by gedw99** [ServiceWeaver/weaver#503]
Is there a way to restrict service instances ? 

My use case is that I am embedding NATS Jetstream. It’s standard practice to run 3 instances per region / data center. Then NATS forms a global cluster between all regions. 

So I need to tell Weaver to keep the NATS service a 3 per regions. 

On a desktop single or multi is will still work too , since nats is just another service.

At days 2 ops when you need to upgrade Nats Service the blue Green system would do its thing. Nats supports a reasonably simple way to upgrade one at a time. It’s called “lane duck” mode and it drains connections , upgrades and tells k8 as it cycles through. This is build into nats :) so it’s just a matter of looking at how NATS operator does it. Luckily it’s available at: https://github.com/nats-io/nack

the official NATS operator calls Nack.  you can see lame duck config here: https://github.com/nats-io/k8s/blob/8448027512f5c332ff62e7ef39a910fc15c05516/helm/charts/nats/files/config/config.yaml#L6

**Comment by spetrovic77** [comment]
Hi @gedw99,

Would you mind clarifying if you are suggesting that Service Weaver integrates NATS into its framework, or you are happy to keep using NATS and Service Weaver as two separate things, but you need Service Weaver to inter-operate better with NATS?

If it's the latter, I think your request makes perfect sense. You basically want to control how many instances of a component we create in each region. We have been meaning to add this support. Just to make sure, you don't want "at least 3 instances per region", you want "**exactly** 3 instances per region", is that right?

I presume you're also looking at the `weaver-gke` deployer, which is our cross-regional GKE deployer? We also have `weaver-kube` deployer, which deploys to a single cluster and can deploy to any Kubernetes cluster.

As an aside, we have been looking into integration with NATS and other Pub/Sub providers. Unfortunately, they all have subtly different semantics. For example, look at [this](https://docs.nats.io/nats-concepts/what-is-nats#nats-quality-of-service-qos) little snippet from the NATS team:

```
At most once QoS: Core NATS offers an at most once quality of service. If a subscriber is not listening on the subject (no subject match), or is not active when the message is sent, the message is not received. This is the same level of guarantee that TCP/IP provides. Core NATS is a fire-and-forget messaging system. It will only hold messages in memory and will never write messages directly to disk.
At-least / exactly once QoS: If you need higher qualities of service (at least once and exactly once), or functionalities such as persistent streaming, de-coupled flow control, and Key/Value Store, you can use [NATS JetStream](https://github.com/nats-concepts/jetstream), which is built in to the NATS server (but needs to be enabled). Of course, you can also always build additional reliability into your client applications yourself with proven and scalable reference designs such as acks and sequence numbers.
```

**Comment by gedw99** [comment]
hey @mishudark 

Thanks for looking into this.  Below I answer each point to try to move this forward...

---

My own slant is to NOT embed, but use the NATS Server binary and then upgrade it using weaver Deployer: https://serviceweaver.dev/blog/deployers.html

Why ?

- So we can upgrade NATS Server binary, without having to upgrade Weaver itself.
- NATS has Lame duck mode or LDB that does exactly what we want for Blue / Green upgrades with no downtime. Here are the relevent touch points: https://github.com/search?q=org%3Anats-io%20LDM&type=code 
- It will also be a nice baseline for Weaver running other stateful components perhaps.  For example i do this with Postresql
- No go .mod bloat for Weaver.  I think that's the only sustainable way actually.

To show you what i mean, I already do it this way on projects. I actually store the versions of NATS Server binary inside NATS itself using the NATS Object Store. I can then upgrade any binary ( not just NATS ) , via NATS CLI itself.  

- https://github.com/nats-io/natscli
- I use overwind for a poor mans K8. https://github.com/DarthSim/overmind on each server.

The other way of doing this pattern to upgrade NATS binary is to use [Syndia](https://www.synadia.com/ngs) to store your binaries on the NATS Server. You can also do it for any Binary or WASM, which i do. I can this the NATS Onion Architecture pattern.

If we embed it:

- Then when you upgrade Weaver, you also upgrade NATS using go.mod.  Its easy to do as seen here: https://github.com/maxpert/marmot/blob/master/stream/embedded_nats.go#L11
- Weaver project gets bloated. BAD

---

3 is typically what NATS needs per region as you have suggested.  It is a good baseline.

- Try it on your laptop with https://github.com/ColinSullivan1/nats-local-supercluster 

---

NATS JetStream is what i was assuming - sorry for not making that clear. So QOS problem is solved as its "At-least / exactly once QoS", not "At most once QoS". 

NATS Jetstream has a new API that cleans up the API and Patterns for usage. I won't go into the details as its too much to explain here, but here is the link: https://github.com/nats-io/nats.go/tree/main/jetstream

---

I get what you mean about wanting to support many Message Brokers, if i can use that jargon. https://gocloud.dev/howto/pubsub/ from the google team would be what i would use.

However, we loose other bits that NATS does like KV, Object Store, Schema Resolution, etc.

---

I can  help on this. Have started to read the docs and code for writing you own Weaver Deployer.

There are decent NATS samples here btw: https://natsbyexample.com

**Comment by spetrovic77** [comment]
Hi @gedw99,

I have to admit that I'm not familiar enough with NATS to make a sensible comment here. :smiley:  But I really like the idea of writing a NATS-centric Service Weaver deployer.

Thank you for your pointers to the Google Cloud Pub/Sub package, this is exactly what we need and we may use it going forward to support Pub/Sub integration.

Since you may be looking at writing your own deployer, feel free to reach out to us on [Discord](https://discord.gg/FzbQ3SM8R5) or via private email at serviceweaver@google.com if you need any help.

I'll also keep this issue open so that people are aware of your efforts here.

**Comment by gedw99** [comment]
Thanks @spetrovic77 

It might be better if I help on the CDK then. That way I can get a feel for your approach and then go for it on a dedicated NATS one.

Can you add me to that issue or direct me to the GitHub branch if and when it happens ?

i can help with NATS testing too for it

**Comment by gedw99** [comment]
Oh I just realised that if you going to use the pub sub part of the CDK then you going to only implement calling that API as a client ?

**Comment by spetrovic77** [comment]
Hi @gedw99 ,

Sorry for the late reply. We're still deciding what to do with Pub/Sub support in general. The Go CDK APIs are also somewhat outdated.

The best feedback you can provide us is actually on writing a new deployer, and we're excited to support you in your journey there 😄 .

**Comment by gedw99** [comment]
Ok so back to NATS it seems ?

You guys need to decide if you want to use the binary.

I use NATS and cockroach db everywhere. Both support clustering . Even couch roach.

both can run on all OS so weave in desktop will be able to use them too.

As I said above i use nats to update binaries and env config over a ton of servers . So I suspect the same will work quite well in weave.

this leads to a deployment a physical topology where 3 k8’s are running stateful service and the rest connect horizontally to where ever the stateful binaries are.

I also run wasm Inside k8. Why am I mentioning this ? Because I treat wasm files ( .wasm ) like any binary like nats or cockroach.  They get managed differently but they get deployed and updated in real time working a deployed k8.

Maybe this helps with working out the design approach . You know weave better than me. A dummy stateful example would be my first step. Something that does hello world with state on disk etc . Just to get going

**Comment by gedw99** [comment]
I think the CDK is the best and easiest way to allow weave to have an agnostic way to talking to different cloud specific systems .

the pub sub is decent. Sure you don’t get everything nats provides but you get enough and they just updated to use the latest nats.

https://github.com/google/go-cloud/releases/tag/v0.33.0

also like all software it’s about the least worst option and the CDK is pretty impressive in what it does and quite clean .

If I had time , which I don’t , I would make a separate repo or use go.work and make an example to start down the road of using it and see how it goes.
