### ISSUE TITLE
Question: How to create multiple http services

### ISSUE THREAD

**Issue by go-kenka** [ServiceWeaver/weaver#504]
I want to provide multiple http services for different clients, I haven't found a good way

**Comment by go-kenka** [comment]
I want to create a program like this, including front-end and admin management, and need to use two listeners to deploy to different domain names, but now there can only be one weaver.Main.

```
├─authservice
│      config.go
│      service.go
│      weaver_gen.go
│      
├─fileservice
│      config.go
│      service.go
├─gateway
│  ├─admin
│  │  │  server.go
│  │  │  weaver_gen.go
│  └─frontend
│      │  server.go
│      │  weaver_gen.go
├─logservice
│      config.go
│      service.go
│      weaver_gen.go
├─siteservice
│      config.go
│      service.go
│      weaver_gen.go
└─userservice
        config.go
        service.go
        weaver_gen.go
```

**Comment by spetrovic77** [comment]
Hi @go-kenka, 

Ah, I see the problem you are facing. There is some flexibility here, as you can attach a `weaver.Listener` to any component, not only `weaver.Main`. But I would really recommend the following, as it is most Go-ey:

- Place main.go at the root of your directory structure.
- Place the `weaver.Main` component in main.go, with two `weaver.Listener`s: `admin` and `frontend`.
- `gateway/admin` and `gateway/frontend` are no longer weaver components, they are regular Go types that take in a listener and a weaver component (i.e., `weaver.Main`), and initialize themselves.

That way, the `weaver.Main` component will end up hosting two servers, which is the best solution.

Alternatively, you can make `gateway/admin` and `gateway/frontend` their own components that implement an empty interface, and declare their respective listeners in the implementation. `weaver.Main` will have a `weaver.Ref` to both. You can initialize your HTTP servers in those components' `Init()` methods. You will likely want to [co-locate](https://serviceweaver.dev/docs.html#config-files) `weaver.Main` with one or both of these components, to avoid running too many containers.

I'm re-opening the issue to make sure either of these work for you.

**Comment by go-kenka** [comment]
Thank you for your answer, I should use the first way. Because the second way is the mode I am using now, the problem with this mode is that if `weaver.Main` is started multiple times, it will cause multiple calls in `Init()` in the ref component.
