### ISSUE TITLE
Limit maximum of replication

### ISSUE THREAD

**Issue by kedric** [ServiceWeaver/weaver#524]
Hello, 

is it possible to make an implemetation have a maximum number of replications?

I'm thinking of the use case of an element of my application that uses resources that are themselves limited 

Use case: 
- a database with a maximum number of connections 
- a cache with a writer and several readers

**Comment by kedric** [comment]
Hi @mwhittaker,

If I lose contact with a replica, I think it should be considered obsolete. if the replica was in demand, I'll have to start a new one.
After that, it's up to me to decide whether to keep a resource margin for myself, so that I can have a period of time when I'm likely to use more resources.

But this means that for a writer/reader case, it's a tricky situation. 

Is there any way of making a leader election system for the second case with what exists?

**Comment by kedric** [comment]
Hi @mwhittaker,

Thank you for this information, I'll see how I can do.

**Comment by rgrandl** [comment]
@kedric, this is somewhat orthogonal, but you can specify the max number of replicas if you use the GKE deployer.
