### ISSUE TITLE
Bazel Support

### ISSUE THREAD

**Issue by lbhdc** [ServiceWeaver/weaver#550]
Hey! I am really interested in exploring how service weaver would fit in a bazel project. 

I asked [in the bazel slack](https://bazelbuild.slack.com/archives/CDBP88Z0D/p1692631964746059) if there was an integration with service weaver, and it was suggested that perhaps there was internal blaze support.

If that support exists, would it be possible to open source it?

**Comment by mwhittaker** [comment]
Hi @lbhdc, we do not have any official bazel support. 

To build a Service Weaver application, you have to run `weaver generate ./...` and `go build`. Does bazel support that?

**Comment by mwhittaker** [comment]
I see. Thanks for explaining; I'm not very familiar with bazel. I'll leave the issue open as a TODO then.

**Comment by mwhittaker** [comment]
Yeah, for sure!

**Comment by rgrandl** [comment]
This is not actionable.
