### ISSUE TITLE
The dashboard seems a little unusual.

### ISSUE THREAD

**Issue by kalifun** [ServiceWeaver/weaver#580]
I followed the official documentation and after starting the service, I noticed that the dashboard would keep reporting errors.
![image](https://github.com/ServiceWeaver/weaver/assets/37646342/f29ba4a5-9f11-4734-a8ba-c0ea5a0048af)
I've noticed that there seems to be a problem with the template, and I'm not sure if I'm misinterpreting it.

https://github.com/ServiceWeaver/weaver/blob/536bcca260218eef352571e31fc61dfaee785faa/internal/status/templates/deployment.html#L165

https://github.com/ServiceWeaver/weaver/blob/536bcca260218eef352571e31fc61dfaee785faa/internal/status/status.pb.go#L136C1-L136C1

```
type Component struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name    string    `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`         // component name (e.g., Cache)
	Pids    []int64   `protobuf:"varint,3,rep,packed,name=pids,proto3" json:"pids,omitempty"` // PIDs of component replicas
	Methods []*Method `protobuf:"bytes,4,rep,name=methods,proto3" json:"methods,omitempty"`   // methods
}
```

I noticed that there is no definition for `Group`, so is that what is causing the `$c.Group` to report an error.

**Comment by rgrandl** [comment]
Great finding @kalifun. This is being fixed in #582.
