### ISSUE TITLE
0.21.2 was not completed

### ISSUE THREAD

**Issue by chenrui333** [ServiceWeaver/weaver#603]
👋 it looks like 0.21.2 release was not completed ([failed action run](https://github.com/ServiceWeaver/weaver/actions/runs/6166298665)), raise this issue for some awareness. Thanks!

relates to https://github.com/Homebrew/homebrew-core/pull/142157

**Comment by mwhittaker** [comment]
Hi @chenrui333. Note that we only make GitHub releases for minor versions (e.g., v0.20.0, v0.21.0) and not for patch versions (e.g., v0.20.1, v0.21.2). We haven't made a GitHub release for v0.21.0 yet, but we will soon. The failing GitHub action you linked to is a bug in our GitHub actions, but it doesn't affect the release.

**Comment by mwhittaker** [comment]
Just made a GitHub release for v0.21.0: https://github.com/ServiceWeaver/weaver/releases

**Comment by samford** [comment]
Thanks! Just to clarify, should we be updating to tagged minor versions that don't have a release (e.g., v0.21.2, v0.21.1, v0.18.1, v0.16.1) or should we only update to versions that have a GitHub release (e.g., 0.21.0, 0.20.0, etc.)?

**Comment by mwhittaker** [comment]
Update to the latest tagged version! Go should do this for you automatically: `go install github.com/ServiceWeaver/weaver/cmd/weaver@latest`
