### ISSUE TITLE
Can Weaver add serializable for the sql.Null* structs?

### ISSUE THREAD

**Issue by bagualing** [ServiceWeaver/weaver#640]
Hi，
Can Weaver add serializable for the sql.Null* structs? 
I think it will be very valuable.

**Comment by mwhittaker** [comment]
> Can Weaver add serializable for the sql.Null* structs?

Unfortunately not. A named struct type is only [serializable](https://serviceweaver.dev/docs.html#serializable-types) if it meets one of the following conditions: 

- It is a protocol buffer (i.e. it implements `proto.Message`).
- It implements `encoding.BinaryMarshaler` and `encoding.BinaryUnmarshaler`.
- It embeds `weaver.AutoMarshal`. 

The `sql.Null*` types are not protocol buffers obviously. And we cannot make them implement `BinaryMarshaler` or `BinaryUnmarshaler` or embed `weaver.AutoMarshal`. You can, however, make type aliases to the `sql.Null*` types and implement the `BinaryMarshaler` and `BinaryUnmarshaler` interfaces yourself: 

```go
type NullByte sql.NullByte
func (n *NullByte) MarshalBinary() (data []byte, err error) { ... }
func (n *NullByte) UnmarshalBinary(data []byte) error       { ... }

type ExampleComponent interface {
        // Note that we're returning `NullByte`, not `sql.NullByte`. 
        Method(context.Context) (NullByte, error)
}
```

Would this approach solve your problem?

**Comment by bagualing** [comment]
I'm still interested in this sql.Null* serialization issue.

Because these days when I write Weaver components, I feel very awkward to deal with these "sql.Null*" types, even use type aliases solution.

Is there a way to natively support sql.Null* in Weaver's codegen.Encoder and codegen.Decoder struct?

Thanks！
