### ISSUE TITLE
The port of the configuration file is not in effect，SERVICEWEAVER_CONFIG=weaver.toml go run . The command runs the configuration file to take effect

### ISSUE THREAD

**Issue by y26s4824k264** [ServiceWeaver/weaver#654]
![image](https://github.com/ServiceWeaver/weaver/assets/54879886/16a750d6-c1aa-4715-abd8-ca6a379a7079)
![image](https://github.com/ServiceWeaver/weaver/assets/54879886/fa9f7989-d6ff-4c46-8e14-8101ee8112c6)

![image](https://github.com/ServiceWeaver/weaver/assets/54879886/1668ff03-5ff3-46e3-9a06-49293df3b49e)

**Comment by mwhittaker** [comment]
The `[single]` section of the TOML config file configures a Service Weaver application run with `go run` and `weaver multi single`. To configure an app run with `weaver multi deploy`, you'll have to add a `[multi]` section like this: 

```toml
[multi]
listeners.hello = {address = "localhost:12345"}
```

**Comment by spetrovic77** [comment]
We've also seen people forget to re-run `weaver generate` after adding a
listener to their component implementation struct, so please be on the
lookout for that if things still don't work after you add the config.

**Comment by gzhh** [comment]
Any else solutions? I met the same trouble. The port of the configuration file is not in effect.
But i used `go run`, after `weaver generate .`.

my config weaver.toml

```
[single]
listeners.hello = {address = "localhost:12345"}
```

listener

```
type app struct{
    weaver.Implements[weaver.Main]
    reverser weaver.Ref[Reverser]
    hello    weaver.Listener `weaver:"hello"`
}
```

weaver version
v0.22.0 darwin/amd64

**Comment by gzhh** [comment]
> Any else solutions? I met the same trouble. The port of the configuration file is not in effect. But i used `go run`, after `weaver generate .`.
> 
> my config weaver.toml
> 
> ```
> [single]
> listeners.hello = {address = "localhost:12345"}
> ```
> 
> listener
> 
> ```
> type app struct{
>     weaver.Implements[weaver.Main]
>     reverser weaver.Ref[Reverser]
>     hello    weaver.Listener `weaver:"hello"`
> }
> ```
> 
> weaver version v0.22.0 darwin/amd64

Use below command is ok.
SERVICEWEAVER_CONFIG=weaver.toml go run .
