### ISSUE TITLE
Deployment of UPX-compressed program failed.

### ISSUE THREAD

**Issue by bagualing** [ServiceWeaver/weaver#658]
I compressed my program with UPX. Then, when I ran it with the Weaver command “weaver single deploy ...”, I got a panic error. Please see the picture below:

![aaa](https://github.com/ServiceWeaver/weaver/assets/5525630/fa34ca3b-2194-4f49-8d9c-7eb18857435c)

I suspect it's caused by the program not decompressing when deploying.

**Comment by spetrovic77** [comment]
Hi @bagualing ,

We store the component communication graph and some other information (e.g., network listeners) in the read-only section of the binary. Our deployers (like `single` in your case) inspect the binary before they run it to learn about the component communication graph and other application properties. We the use this information in a number of places, such as the enforcement of communication paths using mTLS.

Is there any way for you to undo the compression before invoking `weaver single deploy hoh.toml`?

See this file for more information about how Service Weaver stores information inside the application binary:
https://github.com/ServiceWeaver/weaver/blob/main/runtime/bin/bin.go#L99

**Comment by bagualing** [comment]
> Is there any way for you to undo the compression before invoking weaver single deploy hoh.toml?

I think there is no good way at the moment. Because UPX-compressed programs are self-extracting.
