### ISSUE TITLE
Tests failing on MacOS

### ISSUE THREAD

**Issue by Deleplace** [ServiceWeaver/weaver#663]
Apple M1, macOS Ventura 13.6

`go test ./...` is failing at `github.com/ServiceWeaver/weaver/internal/testdeployer`

Below: 2 successive attempts

This may or may not be related to the window "Do you want the application “testdeployer.test” to accept incoming network connections?" showing up, where I need to click OK

<img width="260" alt="image" src="https://github.com/ServiceWeaver/weaver/assets/13508141/de6d01a0-ed58-4b54-b6c6-d278a23c04ac">

**Comment by Deleplace** [comment]
```
--- FAIL: TestHostnameWeaveletAddress (0.00s)
    remoteweavelet_test.go:437: net.LookupIP("deleplace-macbookpro.roam.internal"): lookup deleplace-macbookpro.roam.internal: no such host
D1017 11:47:37.850467 weavelet             5d2bca72 remoteweavelet.go:336                │ Constructed component="testdeployer.a" serviceweaver/logerror="write protobuf length: write |1: broken pipe"
D1017 11:47:37.850470 weavelet             5d2bca72 remoteweavelet.go:491                │ Updated component="testdeployer.a" serviceweaver/logerror="write protobuf length: write |1: broken pipe"
D1017 11:47:37.850476 testdeployer.a       5d2bca72 components.go:58                    │ A serviceweaver/logerror="write protobuf length: write |1: broken pipe"
D1017 11:47:37.850477 testdeployer.b       5d2bca72 components.go:63                    │ B serviceweaver/logerror="write protobuf length: write |1: broken pipe"
D1017 11:47:37.850478 testdeployer.c       5d2bca72 components.go:68                    │ C serviceweaver/logerror="write protobuf length: write |1: broken pipe"
FAIL
FAIL	github.com/ServiceWeaver/weaver/internal/testdeployer	0.771s
```

**Comment by Deleplace** [comment]
This small test fails on my Mac for some reason, without showing any popup window 

```
func TestLookup(t *testing.T) {
	hostname, err := os.Hostname()
	if err != nil {
		t.Fatal(err)
	}
	ips, err := net.LookupIP(hostname)
	if err != nil {
		t.Fatalf("net.LookupIP(%q): %v", hostname, err)
	}
	t.Log(ips)
}
```

->

```
--- FAIL: TestLookup (0.00s)
    lookup_test.go:16: net.LookupIP("deleplace-macbookpro.roam.internal"): lookup deleplace-macbookpro.roam.internal: no such host
```

**Comment by Deleplace** [comment]
Maybe it is just caused by the specific configuration of my machine:

```
% hostname
deleplace-macbookpro.roam.internal
% host deleplace-macbookpro.roam.internal
Host deleplace-macbookpro.roam.internal not found: 3(NXDOMAIN)
```

**Comment by htiennv** [comment]
Hi @Deleplace, 
you can try add:
`127.0.0.1    deleplace-macbookpro.roam.internal` in ` /etc/hosts`

After making these changes, you might need to flush the DNS cache to ensure the changes take effect immediately.
`dscacheutil -flushcache`

For verify, you try: 
`ping deleplace-macbookpro.roam.internal`
the re-run `go test ./...`

**Comment by rgrandl** [comment]
Hi @Deleplace, are the tests still failing on MacOS for you?

**Comment by Deleplace** [comment]
I think the problem wasn't in the Service Weaver code.

Thanks to @htiennv's advice, I can now run the tests without failures.
