### ISSUE TITLE
Is it possible to choose how my components will split into machines?

### ISSUE THREAD

**Issue by Tom910** [ServiceWeaver/weaver#664]
Hi. I started to learn how [weaver](https://github.com/ServiceWeaver/weaver) works and I got some questions related to deploying to many machines. Weaver has a `multi` or `kube` mode which deploy applications into many deployments/machines N components = N machines. But I haven't found a mixed mode, like: I want to deploy component A and component B in machine M1, Component C in machine M2, and Component D in machine M3. Is it possible to do it now?

**Comment by spetrovic77** [comment]
You can [specify](https://github.com/ServiceWeaver/weaver/blob/main/examples/collatz/colocated.toml) the components you'd like to run together on the same machine.

In your example, you would add the following to your TOML file:

```
colocate = [
  [ "A", "B" ]
]
```

All other components will be distributed onto their own machines.

Note that "A" and "B" strings need to be prefixed with the full package path, including your go.mod module path.

**Comment by Tom910** [comment]
@spetrovic77 Thanks for your fast answer. Is it possible to do only for the main process? is it possible to specify group of components, like: component A and component B in machine M1, component C and component D in machine M2:

**Comment by spetrovic77** [comment]
Hi @Tom910 , you can do it for any component, including main. You can do:

```
colocate = [
  [ "A", "B"],
  [ "C", "D"],
]
```

, in which case A and B will be on M1, and C and D on M2. All other components will be on their own machines.

**Comment by Tom910** [comment]
I published an article related to this topic https://amarchenko.dev/blog/2023-10-19-service-weaver/
