### ISSUE TITLE
Component's interface and implementation in separate packages

### ISSUE THREAD

**Issue by yellowblacksnek** [ServiceWeaver/weaver#681]
Hi, I wanted to implement component's interface defined in another package by creating local interface type as suggested in error message and https://github.com/ServiceWeaver/weaver/pull/282. 
Generation runs fine (weaver generate), but on go run I see the following error:
`component implementation struct main.Main has component reference field weaver.Ref[weaver-pg/contract.A], but component contract.A was not registered; maybe you forgot to run 'weaver generate'
component implementation struct main.Main has component reference field weaver.Ref[weaver-pg/contract.B], but component contract.B was not registered; maybe you forgot to run 'weaver generate'
exit status 1
`
The project structure is like this:
![image](https://github.com/ServiceWeaver/weaver/assets/20935674/7c9473ce-4a3f-4f80-aae7-0e035f499dcf)

contract.go
```go
package contract

import "context"

type A interface {
	A(ctx context.Context) error
}

type B interface {
	B(ctx context.Context) error
}
```

a.go
```go
package a

import (
	"context"
	"github.com/ServiceWeaver/weaver"
	"weaver-pg/contract"
)

type A contract.A

type implA struct {
	weaver.Implements[A]
}

func (a *implA) A(ctx context.Context) error {
	return nil
}
```

b.go
```go
package b

import (
	"context"
	"github.com/ServiceWeaver/weaver"
	"weaver-pg/contract"
)

type B contract.B

type implB struct {
	weaver.Implements[B]
}

func (b *implB) B(ctx context.Context) error {
	return nil
}
```

main.go
```go
package main

import (
	"context"
	"fmt"
	"log"
	"github.com/ServiceWeaver/weaver"
	"weaver-pg/contract"
	_ "weaver-pg/a"
	_ "weaver-pg/b"
)

type Main struct {
	weaver.Implements[weaver.Main]
	a weaver.Ref[contract.A]
	b weaver.Ref[contract.B]
}

func Run(ctx context.Context, c *Main) error {
	fmt.Println("hello")
	return nil
}

func main() {
	if err := weaver.Run[Main, *Main](context.Background(), Run); err != nil {
		log.Fatal(err)
	}
}
```

Is the provided work around no longer working?

**Comment by mwhittaker** [comment]
The `contract.A` and `contract.B` components are not implemented, but the `a.A` and `b.B` components are. Can you try changing your `Main` struct to the following and see if that fixes things?

```go
type Main stuct {
    weaver.Implements[weaver.Main]
    a weaver.Ref[a.A]
    b weaver.Ref[b.B]
}
```

**Comment by yellowblacksnek** [comment]
Hi, thanks for replying!
Yes, if I weaver.Ref interfaces from implementation's package, it works. 
But what I was trying to do is to avoid directly referencing implementation's package in Ref's. 
Am I right to assume that it's not possible in the current implementation?

**Comment by mwhittaker** [comment]
Ah, gotcha. Yeah, that is not currently possible.
