### ISSUE TITLE
weaverAutomarshal failure

### ISSUE THREAD

**Issue by ethanwater** [ServiceWeaver/weaver#683]
### weaverAutomarshal not Serializable?

`weaver generate .` works when generating the AutoMarshall for the struct. However when I try to generate a weaver component that returns said struct I receive the following error:

_Method `FetchAccount(context.Context, string) (models.Account, error)` of Service Weaver component "Database" has incorrect return types. Return 0 has type models.Account, which is not serializable. All returns, besides the final error, must be serializable.
models.Account: named structs are not serializable by default. Consider using weaver.AutoMarshal._

This is the struct I am attempting to serialize, it fits all the guidelines stated in: https://github.com/ServiceWeaver/weaver/blob/v0.22.0/weaver.go#L550
```
type Account struct {
	weaver.AutoMarshal
	ID       int
	Alias    string
	Name     string 
	Email    string 
	Password string 
	Tier     int
}
```

The confusion stems from if its not serializable, why does weaver successfully generate the codegen for this?

I have of course attempted to do all the steps provided, however the error still exists. I have also tried to tweak the weaver_gen.go files to fix it (this of course, didn't work either). Am I missing something here? Thanks !

**Comment by ethanwater** [comment]
Never mind, I was able to find a workaround. It seems that if the struct is being marshaled is in another package, it won't be considered serialized in another packages codegen.

**Comment by mwhittaker** [comment]
Hi @ethanwater, yeah this is definitely a shortcoming of `weaver generate`. If package `a` imports package `b`, you have to be careful to `weaver generate` package `b` before package `a`. An easy way to always do this is to run `weaver generate ./...` at the root of your module, which will generate code for packages in the right order :)
