### ISSUE TITLE
The parent context is not propagated to the component when deploying in "single process" mode

### ISSUE THREAD

**Issue by zailic** [ServiceWeaver/weaver#695]
There could be situations where the component would need the parent context when is initializing. Apparently this is not possible when the application is running in the single process mode because a new context instance is provided when `Init` method of component is called:
![Screenshot 2023-12-21 163701](https://github.com/ServiceWeaver/weaver/assets/2317627/9c2ce317-33d3-4161-b305-a1d8e269abe3)
https://github.com/ServiceWeaver/weaver/blob/main/internal/weaver/singleweavelet.go#L285-L290
Is there any reason why there is not used the parent context?

**Comment by mwhittaker** [comment]
I agree we should use a better context! Feel free to open a PR fixing that if you're keen, but otherwise we'll get around to fixing it :)

**Comment by mwhittaker** [comment]
Oh, you already opened a PR! Awesome :)

**Comment by zailic** [comment]
> Oh, you already opened a PR! Awesome :)

yes :), thanks for the review!
