### ISSUE TITLE
Kube support Apple Silicon M2

### ISSUE THREAD

**Issue by cage1016** [ServiceWeaver/weaver#697]
```
kubectl apply -f $(weaver kube deploy kube_deploy.yaml)
```

As [Service Weaver Docs](https://serviceweaver.dev/docs.html#kube) documentation deploy to local Kubernetes but got error message  

```
$ kubectl logs weaver-main-c7d548af-4de23858-6cf988775f-clw9n
NewBabysitter: create envelope: NewEnvelope: connect to weavelet: read protobuf length: EOF
-----BEGIN STDERR-----
Cannot run macOS (Mach-O) executable in Docker: Exec format error

-----END STDERR-----
exit status 126
```

**Comment by gedw99** [comment]
hey @cage1016 what are you using to run docker / k8 ?

I am also on a m2 Mac and use Orb Stack.  I used to use Docker on Mac etc, but am very happy with Orb Stack.  So it might help ...

**Comment by rgrandl** [comment]
This work has been deprioritized for now
