### ISSUE TITLE
metrics and tracing support for gin?

### ISSUE THREAD

**Issue by dfang** [ServiceWeaver/weaver#716]
I noticed  these in the docs 

```
If you pass an http.Handler to the weaver.InstrumentHandler function, it will return a new http.Handler that updates these metrics automatically, labeled with the provided label.

If you pass an http.Handler to the weaver.InstrumentHandler function, it will return a new http.Handler that traces an HTTP request every second.
```

what if I use gin or fiber?

**Comment by mwhittaker** [comment]
Hi @dfang! Currently, Service Weaver doesn't have any first class support for gin or fiber. 

Looking at the gin documentation, however, it looks like [a `gin.Engine` implements the `http.Handler` interface](https://pkg.go.dev/github.com/gin-gonic/gin#Engine.ServeHTTP)? So, I think you should be able to use gin with `weaver.InstrumentHandler`. And for fiber, [this adaptor](https://docs.gofiber.io/api/middleware/adaptor/) might allow you to do the same?
