### ISSUE TITLE
Is integration with Wire possible?

### ISSUE THREAD

**Issue by aasha-developer** [ServiceWeaver/weaver#729]
I have a very big running prod which is using DDD, so you can consider that
I have many usecase classes and repository classes.
Currently I am using Wire made by Google to initialized all usecases and repositories (well also handlers and others) for me.
I am trying to migrate to service weaver without fixing too many codes especially I donnot want to touch the inner layers of my ddd code.
Is there a way that I can pass my usecase which is injected by wire into a weaver component class so that I can expose it to other components?
Or should I give up and change every class into a weaver component and remove wire?

**Comment by mwhittaker** [comment]
Hi @aasha-developer! You can definitely integrate [wire](https://github.com/google/wire/tree/main) with Service Weaver. I would say there are two things to note here.

First, Service Weaver already does something similar to wire when constructing components. You can have a very complex component dependency graph, but Service Weaver automatically instantiates all the components for you. You don't have to call a bunch of constructors.

Second, if you have some internal state of a component that you want to initialize with wire, you're free to do so! Just add an `Init` method to a component and perform the initialization in there.
