### ISSUE TITLE
feat: adding a Global Config Default Configuration

### ISSUE THREAD

**Issue by godcong** [ServiceWeaver/weaver#732]
In the process of using Weaver, I found that I could not set the default value of Config.
This makes it impossible to use the correct settings when you have not configured config.toml.
We hope to add a setting for the default Config value at startup.

```
type Main struct {
	weaver.Implements[weaver.Main]
	weaver.WithConfig[config.Config]
}

func (m *Main) Init(ctx context.Context) error {
	
        // config only can loads from toml?
        // fmt.Println("config:", m.Config())
	return nil
}

```

**Comment by rgrandl** [comment]
@godcong, can you elaborate on which settings would you like to have default values for, if you don't have them configured in `config.toml`?

**Comment by renanbastos93** [comment]
Based on this issue I believe that he wants to have the possibility to set dynamic variables globally like environment=dev, debug=true, database=root@localhost, etc

**Comment by godcong** [comment]
I think sometimes there are values that don't need to be set, but ignoring them can cause errors...
I shouldn't write all parameters in config.toml.

As @renanbastos93 said, there are some values which by default should not be empty.

The flow I would like should be:
Load defaults -> load configuration (override if set) -> use it.
Instead of:
Default null -> load config (null if not set) -> use it
