### ISSUE TITLE
looking forward to update component interface 

### ISSUE THREAD

**Issue by seiferli** [ServiceWeaver/weaver#733]
We currently have a set of microservices. On the premise of ensuring the workload of maintenance, we hope to make a version that merges services. However, we encountered a problem. The original microservices used gRPC to call each other. When migrating to weaver, Function parameter passing of COMPONENT INTERFACE only supports basic types, such as int string bool ... Is there any plan for Weaver to support custom parameter types when passing parameters in components? Very much looking forward to adding this feature! thanks.

**Comment by rgrandl** [comment]
@seiferli is this still an issue for you?
