### ISSUE TITLE
Best Practice for serving HTTP/S Traffic

### ISSUE THREAD

**Issue by naivary** [ServiceWeaver/weaver#734]
It would be great if we get a blog post on how to serve http/s traffic with Service Weaver with best practices. I don't mean the general way of using a `weaver.Lister`. I mean how to structure it around Service Weaver Components and how to interact with them?

**Comment by rgrandl** [comment]
We have this on our agenda.

**Comment by renanbastos93** [comment]
It is a good Idea maybe we can to organize this idea and create a new document togethers.

**Comment by rgrandl** [comment]
This work has been deprioritized for now
