### ISSUE TITLE
https://serviceweaver.dev/examples.html broken for safari

### ISSUE THREAD

**Issue by gedw99** [ServiceWeaver/weaver#737]
works in chrome but not safari for playing the videos.

**Comment by renanbastos93** [comment]
I have tested using Safari I got it errors:
status code: `HTTP/1.1 206 Partial Content`
<img width="471" alt="image" src="https://github.com/ServiceWeaver/weaver/assets/8202898/66138a0a-27ed-44c3-a0bf-f013bf2c8a4a">
<img width="471" alt="image" src="https://github.com/ServiceWeaver/weaver/assets/8202898/9eda6a6f-221a-4283-aa7f-3ebb665ca65a">

I don't know the approach we need to do.
