### ISSUE TITLE
The issue of errors in cross package serialization processing

### ISSUE THREAD

**Issue by xinjiayu** [ServiceWeaver/weaver#739]
When the defined structure and the processed program are not in the same package in a program, it will affect the serialization processing. Why not use the encoding/gob package for cross package serialization processing?

**Comment by flouthoc** [comment]
I am facing a similar issue that service-weaver's `weaver.AutoMarshal` is failing to recognize other structs in different package which are also serialized using `weaver.AutoMarshal`

My use-case is similar to this

Package 1 -> Contains a complex struct , lets call it A ( serialize using `weaver.AutoMarshal`  )
```go
type A struct {
        weaver.AutoMarshal
         fields...
  }
 ```
Package 2 -> Contains a nested struct  with a field composed of struct from `package 1` 
```go
type B {
      weaver.AutoMarshal
      field A
      fields...
  }
  ```
  
  Now `weaver generate` fails to generate bindings for my type B saying that `A` is not serializable although I already did `weaver generate` for the first type.
  
  
I am new to service weaver and types in my projects are very complex and nested and till now `weaver.AutoMarshal` is not working very well for me, any hints on above issue ?

**Comment by rgrandl** [comment]
@flouthoc, what you described it should work with weaver. 

There are 2 possible scenarios why you might have issues with this:
1) You forgot to run weaver generate in all packages in the right order; best is you run `weaver generate ./...` from your root directory
2) your A or B type might have other fields that are not serializable, which is unclear from your description

**Comment by flouthoc** [comment]
@rgrandl Thanks for the quick reply, it seems my mistake was not running `weaver generate ./..` from root directory and I was manually doing it maybe that was causing unordered codegen.
