### ISSUE TITLE
How do I call the written component in the program in a conventional way? 

### ISSUE THREAD

**Issue by xinjiayu** [ServiceWeaver/weaver#746]
How do I call the written component in the program in a conventional way? That is, directly accessing the method of a component in the program. Thank you.

**Comment by rgrandl** [comment]
Service Weaver components are only callable by other components in the same application. If you want another application to call your Service Weaver application, you have to create a network listener and manage that connection (e.g., HTTP, gRPC). See https://serviceweaver.dev/docs.html#step-by-step-tutorial-listeners.
