### ISSUE TITLE
context propagtion

### ISSUE THREAD

**Issue by reza7957** [ServiceWeaver/weaver#750]
I want to propagate contextual data shuch as UserID from a service to another. It works in single deploy and using context.Context. however it does not work in multi processec deployment. do I have to use OpenTelemetry propation for this purpos? and how?
please help If you know. thanks in advance

**Comment by rgrandl** [comment]
Hi @reza7957, we allow the propagation of a very few things from the context between services that run in different processes (e.g., trace spans). Our recommendation is to add a new field to your method (in your case the UserID) to propagate things between services. 

That's correct, any distributed deployer (including multi) doesn't propagate random context information.
