### ISSUE TITLE
initialize once in multi deploy mode

### ISSUE THREAD

**Issue by dfang** [ServiceWeaver/weaver#756]
```
type T interface {
}

type impl struct {
	weaver.Implements[T]
}

func (i *impl) Init(ctx context.Context) error {
   // setup asynq server and mux here
   // https://github.com/hibiken/asynq
   
   /*
    how can I run code here once when running with `weaver multi deploy weaver.toml`
  */

   return nil
}
```

when start with `weaver single deploy weaver.toml`, this works.
but when I run  `weaver multi deploy weaver.toml`,  there will duplicate queues with different hosts.

**Comment by rgrandl** [comment]
@dfang, you are right, with `weaver multi` deployer, we run two replicas of each component (including main). If you want to initialize something only once, you will have to rely on an external mechanism like redis or something else.
