### ISSUE TITLE
Version mismatch with weaver-kube

### ISSUE THREAD

**Issue by eminetto** [ServiceWeaver/weaver#773]
I'm encountering an error when attempting to deploy an application to Kubernetes:

```
weaver kube deploy config.yaml

ERROR: The binary you're trying to deploy ("bin/microservices") was built with
github.com/ServiceWeaver/weaver module version v0.24.2 (internal version v0.24.0).
However, the 'weaver-kube' binary you're using (v0.23.2) was built with weaver
module version v0.23.2 (internal version v0.23.0). These versions are incompatible.

We recommend updating both the weaver module your application is built with and
updating the 'weaver-kube' command by running the following.

	go get github.com/ServiceWeaver/weaver@latest
	go install github.com/ServiceWeaver/weaver-kube/cmd/weaver-kube@latest

Then, re-build your code and re-run 'weaver-kube deploy'. If the problem
persists, please file an issue at https://github.com/ServiceWeaver/weaver/issues
exit status 1
make: *** [run-kube] Error 1
```
I'm using the last version of both projects, which are:

- weaver-kube: [v0.23.2](https://github.com/ServiceWeaver/weaver-kube/releases/tag/v0.23.2)
- weaver: [v0.24.2](https://github.com/ServiceWeaver/weaver/releases/tag/v0.24.2). When I use `go get github.com/ServiceWeaver/weaver@latest` this is the version that is installed

**Comment by renanbastos93** [comment]
It looks like we are forced to use the same version of Weaver on Weaver-Kube.
I based on this commit: https://github.com/ServiceWeaver/weaver-kube/pull/98/files

**Comment by renanbastos93** [comment]
@eminetto Maybe you could try downgrading the Weaver version in your go.mod and reinstalling the binary via go install. Have you tried that?

**Comment by rgrandl** [comment]
@eminetto, can you try to install the latest version of weaver kube?  `go install github.com/ServiceWeaver/weaver-kube/cmd/weaver-kube@v0.24.3`

We updated the weaver to 0.24.2, but we forgot to create a new tag for weaver kube that points to weaver 0.24.2. Sorry about that.

**Comment by eminetto** [comment]
It worked @rgrandl Thanks!
