### ISSUE TITLE
Weaver generate process is not finished

### ISSUE THREAD

**Issue by taitasu555** [ServiceWeaver/weaver#774]
[In this tutorial](https://serviceweaver.dev/docs.html). I ran `weaver generate . `, but nothing worked after about 10~15 minutes.  Should I change the version of go or weaver?

### Version
- M1 max macbook pro
- go1.22.1 darwin/arm64
- weaver v0.24.2 darwin/arm64

**Comment by taitasu555** [comment]
I downgrade go version 1.20.1 darwin/amd64, but still didn`t work

**Comment by renanbastos93** [comment]
**My laptop settings:**
```
Apple M1 Pro
16GB
macOS: Sonoma 14.5
```

**My versions:**
```
Weaver version: v0.24.2
Go version: v1.22.3
```

**It works on:**

**Command:**
``` 
$ time weaver generate ./...
# output: weaver generate ./...  0.81s user 0.74s system 271% cpu 0.573 total
```

I did a downgrade to test your Go version too. The result was:
```
$ time weaver generate ./...
# output: weaver generate ./...  93.43s user 18.33s system 318% cpu 35.110 total (first build)
# weaver generate ./...  0.77s user 1.07s system 345% cpu 0.532 total (last build)
```

**Important comments:**
This is normal because it is the first build of your project. The next builds will be faster.

**Comment by rgrandl** [comment]
Thanks @renanbastos93. It works for me too.

@taitasu555 do you still have these issues?

I've tried:
* Apple M1 Pro
* macOS: Sonoma 14.5
* go1.22.4 darwin/amd64
* weaver v0.24.2 darwin/amd64

**Comment by taitasu555** [comment]
Thank you for replying @rgrandl  @renanbastos93 

it still doesn't work on my laptop.  

```
 time weaver generate ./...

not finished and kill the process
0.01s user 0.02s system 0% cpu 1:35.66 total
```

using security software and VPN may causes this problem.


I've also tried:
Apple M1 Pro
macOS: Sonoma 14.5
go1.22.4 darwin/amd64
weaver v0.24.2 darwin/amd64

**Comment by rgrandl** [comment]
@taitasu555 is this still an issue?
