### ISSUE TITLE
Duplicate Method Executions in weavertest.RPC Mode

### ISSUE THREAD

**Issue by meifannao** [ServiceWeaver/weaver#779]
When using weavertest.RPC for testing, I've observed that multiple instances of the same component are started, which is expected. However, when I call a method, each component instance seems to execute the method. Is this behavior correct?

For example, I have the following database table:

```sql
CREATE TABLE user_info (
    id SERIAL PRIMARY KEY,
    username VARCHAR(255) NOT NULL,
    password VARCHAR(255) NOT NULL
);
```
Using weaver to implement a Create method:
```go
type user interface {
    Create(ctx context.Context, username, password string) error
}

type User struct {
    weaver.Implements[user]
    queries *user_db.Queries
}

func (u *User) Init(ctx context.Context) error {
    dsn := "postgres://postgres:qweasd@127.0.0.1:5432/postgres?sslmode=disable"
    conn, err := pgxpool.New(ctx, dsn)
    if err != nil {
        u.Logger(ctx).Error("failed to connect to database", "err", err)
        return err
    }
    u.queries = user_db.New(conn)
    return nil
}

func (u *User) Create(ctx context.Context, username, password string) error {
    u.Logger(ctx).Info("create user", "username", username, "password", password)

    if err := u.queries.CreateUser(ctx, user_db.CreateUserParams{
        Username: username,
        Password: password,
    }); err != nil {
        u.Logger(ctx).Error("failed to create user", "err", err)
        return err
    }

    return nil
}

```
Here is the test code:
```go
func TestCreateUser(t *testing.T) {
    for idx, runner := range weavertest.AllRunners() {
        runner.Test(t, func(t *testing.T, user user) {
            username := fmt.Sprintf("user_%d", idx)
            password := "test_password"

            err := user.Create(context.Background(), username, password)
            assert.NoError(t, err)
        })
    }
}
```
When the runner is weavertest.Local or weavertest.Multi, there are no issues. However, in weavertest.RPC mode, the Create function is called four times as shown in the logs:

![35e5db2146630a9f435e02b37181e8e](https://github.com/ServiceWeaver/weaver/assets/58097859/b21b581f-c095-4598-a6f1-d3910228bcb5)

Additionally, there are two records inserted into the database under RPC mode:
![image](https://github.com/ServiceWeaver/weaver/assets/58097859/496e64b8-3cb4-4145-82d9-5137b34502f1)

**Comment by rgrandl** [comment]
Hi @meifannao, that looks wrong. Thanks for reporting it.

**Comment by rgrandl** [comment]
@meifannao, the `weavertest.RPC` will retry your method by default. This is by design to catch cases where you want a method to not be retriable by default, but you forgot to mark your method as non-retriable. 

In this case, you should add
```
var _weaver.NotRetriable = user.Create 
...
```

when you define/implement your component. More details here: https://serviceweaver.dev/docs.html#components-semantics

I'll improve the doc a little bit to make things clearer.

**Comment by meifannao** [comment]
> @meifannao，`weavertest.RPC`将默认重试您的方法。这是设计用来捕获以下情况：您希望方法默认不可重试，但您忘记将方法标记为不可重试。
> 
> 在这种情况下，您应该添加
> 
> ```
> var _weaver.NotRetriable = user.Create 
> ...
> ```
> 
> 当你定义/实现你的组件时。更多详细信息请见：https://serviceweaver.dev/docs.html#components-semantics
> 
> 我会稍微改进一下文档，让内容更清晰一些。

Thank you! I have verified, and the issue has indeed been resolved.
