### ISSUE TITLE
Is Service Weaver suitable for writing tcp server？

### ISSUE THREAD

**Issue by wind-c** [ServiceWeaver/weaver#785]
I've only seen examples of http.

**Comment by rgrandl** [comment]
@wind-c it should. E.g., you can run a gRPC server to export the listener instead of a HTTP server. We're working on adding an example to our website.

**Comment by wind-c** [comment]
I wrote the tcp server example and the single-process mode is fine. The new question is, in a multi-process, multi-machine, or multi-replica deployment, how do you find out which replica a given client tcp connection is on? How do you route messages to this tcp connection?

**Comment by wind-c** [comment]
The response to the Issue was too slow, and the long wait was too painful.

**Comment by rgrandl** [comment]
I already answered to this question in the other PR. Can you elaborate on what exactly you're trying to do?

Slowness - we've been a little bit overwhelmed with other things, sorry about that. Open source is just one way we contribute to the project.
