### ISSUE TITLE
weaver generate doesn't support go build tags

### ISSUE THREAD

**Issue by Gris87** [ServiceWeaver/weaver#786]
Hi,

I am trying to compile my project: [test.zip](https://github.com/user-attachments/files/16347608/test.zip)

There are 2 files:
- good.go with a build tag `good` that can be normally compiled when `-tags good` provided to `go run` command
- bad.go with a build tag `!good` than contains a lot of syntax errors or other errors/circumstances that makes compilation impossible at the moment

So, when I'm trying to call `go generate ./...` or `weaver generate ./...` I'm getting a compilation error due to errors in bad.go.

What I want to get is a support of go build tags for `weaver generate` in order to make it ignore bad file and use good one.

**Comment by Gris87** [comment]
Hi, any updates?

**Comment by rgrandl** [comment]
@Gris87, is this a blocker for you? I will bring up this issue tomorrow in our group meeting.

**Comment by Gris87** [comment]
It's not so critical, just want to know the status

**Comment by rgrandl** [comment]
@Gris87, you are right; the `weaver generate` command ignores user-defined tags. Would simply adding a --tags option to `weaver generate`, with the same syntax as in the case of `go build`, suffice?

**Comment by Gris87** [comment]
Yes, that will be enough

**Comment by rgrandl** [comment]
Sounds good. I'll work on a PR to add this support.

**Comment by rgrandl** [comment]
Implemented in #796

**Comment by rgrandl** [comment]
go build tags is supported in the latest weaver version (v0.24.5)
