### ISSUE TITLE
Is the project still alive? 

### ISSUE THREAD

**Issue by wind-c** [ServiceWeaver/weaver#790]
Is the project still alive? Is the idea and direction of the project right?
Why didn't anyone answer questions for so long? Are contributors too busy?

**Comment by rgrandl** [comment]
Hey @wind-c. Feel free to describe in more details what you're trying to do.

Otherwise, feel free to ping me on discord and we can discuss in details your issues. We usually do that with people who're trying to adopt weaver and face various issues.
