### ISSUE TITLE
Multi deployer support for gRPC and raw TCP traffic

### ISSUE THREAD

**Issue by rgrandl** [ServiceWeaver/weaver#792]
In the current implementation of the multi-deployer, we have an HTTP proxy that receives the requests handled by the listener. Whenever a request is received, it is forwarded by the HTTP proxy to one of the `main` backends.

However, if users send gRPC or raw TCP requests to the listener, the HTTP proxy will reject them due to malformed messages. We should enhance our `multi` deployer to make the proxy capable of handling not only HTTP traffic.

**Comment by wind-c** [comment]
Good!
Me really looking forward!

**Comment by wind-c** [comment]
@rgrandl , what is the progress so far?

**Comment by rgrandl** [comment]
This work has been deprioritized, and we are currently focused primarily on addressing any critical issues.
