### ISSUE TITLE
multi dashboard doesn't show traffic?

### ISSUE THREAD

**Issue by bowenni** [ServiceWeaver/weaver#793]
Hello! I tried to run the tutorial following https://serviceweaver.dev/docs.html#step-by-step-tutorial. In the `Multiprocess Execution` section the dashboard produced by `weaver multi dashboard` doesn't show any traffic, whereas the previous single process deployment has a nice dashboard with traffic between components visualized:

![image](https://github.com/user-attachments/assets/dd64ea3a-a23b-48fc-a511-ba088d7fb3cc)

**Comment by rgrandl** [comment]
@bowenni thanks for reporting this. Fixed in #794
