### ISSUE TITLE
Add support for Nutanix private cloud

### ISSUE THREAD

**Issue by n4j** [ServiceWeaver/weaver#84]
I want to start this issue to track  [Nutanix](https://www.nutanix.com/) private cloud environment as supported deployment target for ServiceWeaver.

I work at Nutanix and I am willing to drum-up support for ServiceWeaver within Nutanix and get this implemented.

**Comment by spetrovic77** [comment]
That's awesome, Neeraj!

We are going to release a blog post on how to write a deployer soon (next week, I hope), but in the meantime ping us on our [Google Group](https://groups.google.com/g/serviceweaver/) or directly at serviceweaver@google.com if you have any questions.

**Comment by mwhittaker** [comment]
Hi @n4j, we just dropped the blog post on how to write a deployer: https://serviceweaver.dev/blog/deployers.html. I think it will be super helpful in writing a Nutanix deployer!

**Comment by n4j** [comment]
Thanks @mwhittaker 🙂.

Also, can you keep this issue open to track and communicate that Nutanix support is being implemented?

**Comment by rgrandl** [comment]
This is not actionable.
