### ISSUE TITLE
Enabling the errcheck linter

### ISSUE THREAD

**Issue by dnephin** [ServiceWeaver/weaver#90]
Congratulations on the first release! ServiceWeaver looks very interesting and I'm looking for ways to contribute.

I noticed that `errcheck` is disabled with a comment about too many errors. I've found this linter to be useful because unhandled errors can often cause bugs.

Would you be interested in a few small PRs to fix or ignore the current warnings so that the `errcheck` linter can be enabled?

I'll leave some more detail in a comment below about how I'd approach that change.

**Comment by dnephin** [comment]
Initially I'd want to enable it only for production code (not tests), to limit the number of changes required to get it enabled. Something like this:

```yaml
issues:
  exclude-rules:
    - path: '_test\.go'
      linters: [errcheck]
```

I think a bunch of the unhandled errors are safe to ignore (ex: writing an HTTP response from a handler). Those can be ignored with either:

```go
_, _ = w.Write(...)
// or
w.Write(...) //nolint:errcheck
```

Do you have a preference on one of those styles?

----

There are a few cases where it seems like the error simply needs to be returned:

https://github.com/ServiceWeaver/weaver/blob/2ae2abb650843ff5c6dbc76c9934a715fa98f2d0/runtime/logging/query.go#L370-L371

https://github.com/ServiceWeaver/weaver/blob/2ae2abb650843ff5c6dbc76c9934a715fa98f2d0/internal/tool/ssh/impl/babysitter.go#L103-L104

https://github.com/ServiceWeaver/weaver/blob/2ae2abb650843ff5c6dbc76c9934a715fa98f2d0/internal/net/call/call.go#L283

or logged:

https://github.com/ServiceWeaver/weaver/blob/2ae2abb650843ff5c6dbc76c9934a715fa98f2d0/internal/tool/ssh/deploy.go#L107

https://github.com/ServiceWeaver/weaver/blob/2ae2abb650843ff5c6dbc76c9934a715fa98f2d0/internal/status/dashboard.go#L177

A log here to inform the user that the port is in use would probably help avoid confusion when perfetto isn't able to display the trace.

https://github.com/ServiceWeaver/weaver/blob/2ae2abb650843ff5c6dbc76c9934a715fa98f2d0/runtime/perfetto/db.go#L526

----

The remaining cases of unhandled errors seems to be mostly in these two categories:
1. starting goroutines with a function that returns an error - in a few of these cases the only possible return value is `ctx.Err`. I wonder if the error return value could be removed from the function signature in those cases.
2. sending an RPC response from an RPC handler when the operation is performed in a goroutine. In these cases I expect the error is also safe to ignore because the client receives the error response, and the caller doesn't care about it.

**Comment by ghemawat** [comment]
Hi Daniel,

We would love to take you up on your offer to help enable errcheck.

Your suggestion on just focusing on non-test code for now seems spot on.

> _, _ = w.Write(...)
> // or
> w.Write(...) //nolint:errcheck

I think I would prefer the latter since it will be easier to spot and search for. So let's go with the //nolint:errcheck approach.

Thanks for offering to help and your clear write-up of the types of changes that would be needed.
