### ISSUE TITLE
Add support for Support for GCP Cloud Run

### ISSUE THREAD

**Issue by crashdump** [ServiceWeaver/weaver#95]
Very interesting approach, thanks for the amazing work.

I have a use case where the application is sometimes deployed:
* on premise - low traffic environment, simple deployments,
* cloud run - for much larger SaaS-type environments

A deployer for could run would be very welcome, any plans for this?

**Comment by szabba** [comment]
I'm not a project contributor, just a passer-by, but I don't think Cloud Run allows for something like the routing/sharding support in Service Weaver to be implemented easily.

**Comment by rgrandl** [comment]
Thank you for your inquiry. This would be a great deployer for sure. We are having some discussions with the Cloud Run team on this. We don't have a timeline, and a concrete plan for an eventual integration yet. 

@spetrovic77 might be able to add more on this.

**Comment by spetrovic77** [comment]
We would love to see community contribution for writing various deployers. Like @szabba mentioned, there are some issues that may be hard to support for Cloud Run, but I think it's fine if routing/sharding isn't supported out of the box.

@crashdump: if you are interested in driving an implementation of a Cloud Run deployer, please let us know. In that case, re-open the issue or create a new one, and we'll try to support you.

Note that we plan to release a guide on writing deployers soon on our blog at https://serviceweaver.dev.
