### ISSUE TITLE
switch logger to golang.org/x/exp/slog

### ISSUE THREAD

**Issue by komuw** [ServiceWeaver/weaver#96]
Currently weaver is using a custom logger; https://github.com/ServiceWeaver/weaver/blob/main/logger.go, https://github.com/ServiceWeaver/weaver/tree/main/runtime/logging   

There's a proposal to bring structured logging to the Go standard library. That proposal looks likely to be accepted; It was marked as; 
```
Based on the discussion above, this proposal seems like a likely accept.
— rsc for the proposal review group
```
2days ago: https://github.com/golang/go/issues/56345#issuecomment-1450760728 

An implementation of that proposal already exists at; https://pkg.go.dev/golang.org/x/exp/slog  

Since weaver is just starting, I think it should switch to `golang.org/x/exp/slog` early on. It does not have to do so right away, we can wait [a few more days](https://github.com/golang/proposal#accepted) to see if the exp/slog proposal is accepted upstream

**Comment by spetrovic77** [comment]
Thanks for reporting.

Our logger API is based on the `slog` api. However, our logger needs to intercept all the logs, in order to store them in the appropriate logs storage (e.g., Google Cloud Logging, local files). So we can't use the slog package directly.

**Comment by flowchartsman** [comment]
Could you please provide a bit more detail on why this was closed? Specifically, I think it could help to clarify how `slog` integration is not possible.  From where I sit, the necessity of intercepting all logs doe not preclude using `slog`, and I have an internal service library implementation that does exactly this via a common logging interface, while also providing access to creating new handlers through we well-defined interface.  What's to prevent ServiceWeaver from adopting a similar approach?

Given that `slog` is intended to serve as a stdlib-standard interface to structured logging, would you at least consider reopening this issue until the API stabilizes before deciding to forgo `slog` entirely?
